import assert from 'node:assert/strict';
import fs from 'node:fs';
import {fetchBytes,createResourceQueue,createPreviewHall} from '../dist/progressive-loading.js';
const root=new URL('../',import.meta.url);
let attempts=0;
const good=async()=>({ok:true,arrayBuffer:async()=>new Uint8Array([1,2,3]).buffer});
const data=await fetchBytes('fixture',{fetcher:async()=>{if(++attempts===1)throw Error('reset');return good();}});
assert.equal(data.byteLength,3);assert.equal(attempts,2);
let signal;
await assert.rejects(fetchBytes('stalled',{timeout:10,attempts:1,fetcher:async(_,options)=>{signal=options.signal;return {ok:true,arrayBuffer:()=>new Promise(()=>{})};}}),/timed out/);
assert.equal(signal.aborted,true);
await assert.rejects(fetchBytes('missing',{attempts:1,fetcher:async()=>({ok:false,status:404})}),/404/);
const queue=createResourceQueue(2);let active=0,maximum=0;
await Promise.all(Array.from({length:8},(_,i)=>queue.add(async()=>{maximum=Math.max(maximum,++active);await new Promise(resolve=>setTimeout(resolve,2));active--;return i;})));
assert.equal(maximum,2);
const layout=JSON.parse(fs.readFileSync(new URL('dist/data/gallery-layout.json',root)));
const hall=createPreviewHall(layout);assert.equal(hall.group.children.length,6);assert.ok(hall.group.children.every(x=>x.isMesh&&!x.material.map));hall.dispose();
const app=fs.readFileSync(new URL('dist/museum.js',root),'utf8');
assert.ok(app.includes('roomData=initialData.rooms'));
assert.ok(!app.includes("await fetch('./data/"));
assert.ok(!app.includes('addCanonicalPrism'));assert.ok(!app.includes('avoidPrism'));
assert.ok(!app.includes("await new GLTFLoader().loadAsync('./assets/gallery"));
assert.ok(app.includes('requestAnimationFrame(()=>enhance())'));
const canon=layout.rooms.flatMap(r=>r.exhibits).filter(e=>e.id.startsWith('canon-'));
assert.equal(canon.length,3);assert.ok(canon.every(e=>Math.abs(e.x)===4.25&&!e.kind));
assert.ok(fs.readFileSync(new URL('dist/index.html',root),'utf8').includes('href="./archive.html"'));
console.log('PASS: stalled response abort, retry, HTTP failures, bounded image concurrency, immediate untextured hall, three wall text panels, independent reading entry');
