"""Append the R159 application layer once; preserve inherited fields/history."""
from pathlib import Path
import copy,hashlib,json
HERE=Path(__file__).resolve().parent;ROOT=HERE.parent.parent;REL=str(HERE.relative_to(ROOT))
NOTE=REL+'/Body_Frame_Referent_and_Coupling_v0_1.md';PATH=ROOT/'UCT_FORMAL_GRAPH.json';raw=PATH.read_bytes();g=json.loads(raw)
assert g['revision']=='R158-v1.0'
old=copy.deepcopy(g);sha=hashlib.sha256((ROOT/NOTE).read_bytes()).hexdigest()
def save(name,value):(HERE/name).write_text(json.dumps(value,ensure_ascii=False,indent=2)+'\n')
nodes=[]
def add(suffix,kind,statement,domain,quantifiers,section,status,proof,limits):
 n=dict(id='R159:'+suffix,kind=kind,label=suffix.replace('_',' ').title(),statement=statement,domain=domain,scope=domain,source=NOTE+' '+section,source_lineage=NOTE+' '+section,status=status,proof=proof,counterexamples_and_limits=limits)
 n['formal_contract_R159']=dict(object_domain=domain,quantifiers=quantifiers,bearer_time_signature='Actual instance fixes P,I,complete K; trial tokens differ while lineage may be retained. Internal r,k and external referent c/E have different sorts. Abstract example is not an actual organism.',source_anchor=dict(path=NOTE,sha256=sha,locator=section),premise_routes=[],purpose='Explain erroneous body attribution inside actual/experiential organization while separating reference, anatomical truth and coupled roles.',thought_experiments=NOTE+' §7',open_obligations=['F153-09','F153-10','F153-11','F153-12','F153-17'],machine_formalized=False)
 nodes.append(n);return n['id']
c=add('ANCHOR_BINDING_CONTRACT','DEFINITION_AND_ASSUMPTION_PACKAGE','For a fixed admitted actual P,I,complete K,D,Phi,h, internal sorted tokens r,k support grounded K-relations Anchor(r),Bind(r,k),Use(r,k). theta_frame is their conjunction, with fixed/transported parameters. A separately grounded partial psi maps representation tokens to external E; organism anatomical membership M(O(P),psi(k)) is not internal Bind. No h(c) is asserted unless c is in its declared carrier.','Selected installed body-frame organization on one actual-token domain; external reference/organism-membership interpretation is separately declared.','Each instance satisfies every conjunct jointly; no universal necessary/sufficient F_O condition. Logical toy satisfiability does not assert physical realization.','§§2–3','DECLARED_ACTUAL_APPLICATION_CONTRACT','Definition plus independent actual-grounding assumptions; finite r/k/c/member witness demonstrates only abstract consistency.','Name/observer meaning does not install Bind/Use; finite protocol condition bits are not complete neural K; undefined psi/M requires domain restriction.')
t=add('FRAME_RELATION_TRANSPORT','CONDITIONAL_STRUCTURAL_APPLICATION','Given R157:COORDINATE_TRANSPORT and ANCHOR_BINDING_CONTRACT on the same instance, D|=theta_frame(r,k) iff Phi|=theta_frame(h(r),h(k)). False external anatomical membership does not logically negate the installed internal relation; this does not establish a familiar F_O interpretation.','Exactly the common actual P,I,K,D,Phi,h and internally sorted theta_frame from the full contract. External correctness is not a hidden K-premise.','For every admitted tuple/instance satisfying the simultaneous contract and transport premises; not every actual organism is asserted to realize that contract.','§4','MANUAL_CONDITIONAL_C1_APPLICATION','Substitute the grounded K-formula and correctly sorted internal tuple into R157 preservation. External c need not be in the h-domain. Conjunction transport yields a selected relation, not autonomous substructure.','No h on external c without expanded sorts; no report-to-F, no empirical proof of C1, no claim that reference/world changes preserve every K-fact.')
w=add('COUPLED_ROLE_WITNESS','ABSTRACT_COUNTEREXAMPLE_SCHEMA','For b,a in {0,1}, 0<t_O,t_A<1, lambda,mu>0, o=b-t_O+lambda*b*a and q=a-t_A+mu*a*b dissociate by sign at (1,0) and (0,1), yet o(1,1)-o(1,0)=lambda and q(1,1)-q(0,1)=mu are positive. Therefore this explicit schema has role dissociation and graded cross-modulation simultaneously.','Declared finite abstract two-input family with strictly bounded thresholds and positive couplings; not measured neural states or fitted human output laws.','For every parameter tuple in the declared domain; nonempty exact witness t_O=t_A=1/2,lambda=mu=1/4. Sign categories apply only to these toy readouts.','§5','MANUAL_EXPLICIT_COUNTERMODEL_WITH_BOUNDED_CHECKS','At (1,0), o=1-t_O>0,q=-t_A<0; at (0,1),o=-t_O<0,q=1-t_A>0. Subtraction at the fixed other-coordinate corners gives the two positive couplings. All hold together.','Classic algebra, not new mechanism; zero coupling retains sign pattern, outside stated positive-coupling claim. No subjective F assignment, group means fit, or universal neural independence conclusion.')
b=add('SELECTED_OWNERSHIP_APPLICATION','OPEN_BRIDGE_APPLICATION','Compare H_B body-frame binding/use with source modulation and H_A ownership solely determined by a separately grounded source-attribution organization. Actual erroneous Bind can refer via psi to an anatomical nonmember without changing actual bearer by definition. Identifying its intrinsic presentation as familiar ownership requires fixed independent B_min, physical relational witnesses and fallible target evidence.','Restricted human body-frame/remapping application motivated by the declared moving-hand protocol, not a universal self or basal-experience gate.','Two predeclared candidate explanations, not necessary/sufficient biconditionals. Full hidden source states cannot be equated with questionnaire values.','§§5–6','OPEN_POSITIVE_APPLICATION_WITH_EXPLICIT_FAILURE_CRITERIA','Proposal places actual internal error organization under C1, with anatomical truth/reference and selected target interpretation separate. Prior protocol constrains reports, not an exhaustive neural realization.','Tool tracking may satisfy weak frame/use descriptors; post-hoc target refitting forbidden; body-slot discriminant, complete realization and independent F measurement remain open.')
rule=dict(id='r159_frame_relation_transport',all_of=['R157:COORDINATE_TRANSPORT',c],conclusion=t,statement=next(x['statement'] for x in nodes if x['id']==t),proof_sketch=next(x['proof'] for x in nodes if x['id']==t),source=NOTE+' §4',kind='CONDITIONAL_APPLICATION',review='MANUAL_SAME_INSTANCE_APPLICATION')
rule['formal_contract_R159']=dict(premise_connective='AND',bindings_required=['same P,I,complete K,D,Phi,h in both premises','theta_frame a grounded K-formula; r,k in internal correctly sorted carriers','fixed/transported parameters; external psi/E/c not silently mapped by h'],quantification='For each jointly admissible actual instance; physiological premises not discharged by abstract satisfiability.',proof_location=NOTE+' §4',source_sha256=sha,machine_proof=False)
next(x for x in nodes if x['id']==t)['formal_contract_R159']['premise_routes']=[dict(rule=rule['id'],all_of=rule['all_of'])]
amend=[]
for ident,text in [
 ('R158:TARGET_SPLIT','Insert internal representation token k and separately grounded external reference psi(k)=c. Internal K-isomorphism applies to k, not automatically to external c; organism anatomy differs from neural support membership.'),
 ('R158:TARGET_SPECIFIC_BRIDGE_PROFILE','Ownership/agency roles may be distinguished while strengths cross-modulate. The two candidate directions are not claims of uncoupled laws or sufficient F bridges.'),
 ('R157:DEFINABLE_SELECTOR_SETUP','For body attribution, correctly sorted internal r,k may enter a K-formula; external candidate c cannot enter h-domain merely by being its represented content. Expanded environmental sorts/realization must be declared separately.')]:
 n=next(x for x in g['nodes'] if x['id']==ident);n['formal_contract_R159']=dict(amends='Typing/application clarification only; inherited statement and contracts retained.',effective_reading=text,source_anchor=dict(path=NOTE,sha256=sha,locator='§§3–6,8'),machine_formalized=False)
 amend.append(dict(id=ident,effective_reading=text,status='SCOPE_REFINEMENT_WITH_OPEN_GROUNDING'))
links=[dict(**{'from':x,'to':y},relation=z) for x,y,z in [(w,b,'counterexample to uncoupling shortcut; not evidence that this is a neural law'),('R158:TARGET_SPECIFIC_BRIDGE_PROFILE',b,'positive application refinement; target semantics remain open'),('B:BAC',b,'methodological criteria and failure obligations, not a deduction'),('R156:SNAPSHOT_USE_LIMIT',c,'installed consumers remain independent physical grounding obligation'),('A:U1',b,'context: no selected-body clause added to basal existence')]]
g['nodes']+=nodes;g['rules'].append(rule);g['context_links']+=links
for prior,now in zip(old['nodes'],g['nodes']):assert {k:v for k,v in now.items() if k!='formal_contract_R159'}==prior
assert g['rules'][:len(old['rules'])]==old['rules'] and g['context_links'][:len(old['context_links'])]==old['context_links']
ids=[x['id'] for x in g['nodes']];rid=[x['id'] for x in g['rules']];assert len(ids)==len(set(ids)) and len(rid)==len(set(rid))
deps={x:set() for x in ids}
for r in g['rules']:
 assert r['all_of'] and r['conclusion'] in deps and all(x in deps for x in r['all_of']);deps[r['conclusion']].update(r['all_of'])
done=set();active=set()
def visit(x):
 assert x not in active
 if x in done:return
 active.add(x)
 for p in deps[x]:visit(p)
 active.remove(x);done.add(x)
for x in ids:visit(x)
g['revision']='R159-v1.0';g['base_commit']='b536254cff1472cf43657323b9a6046092028e01'
g['research_R159']=dict(start_head=g['base_commit'],parent_graph_sha256=hashlib.sha256(raw).hexdigest(),note=NOTE,new_nodes=4,new_rules=1,status='INTERNAL_FRAME_REFERENT_APPLICATION_AND_COUPLED_ROLE_LIMIT_BRIDGE_OPEN',contract='formal_contract_R159 for four new entries/one rule and three explicit refinements only; historical fields intact',global_semantic_proof=False,empirical_validation=False)
PATH.write_text(json.dumps(g,ensure_ascii=False,indent=2)+'\n')
save('MAP_EXTENSION.json',dict(nodes=nodes,rules=[rule],context_links=links));save('AMENDMENTS.json',dict(entries=amend))
save('MAP_AUDIT.json',dict(status='PASS_SCOPED_APPLICATION_AUDIT',nodes=len(ids),rules=len(rid),new_nodes=4,new_rules=1,unique_ids=True,all_rule_endpoints_present=True,acyclic=True,inherited_fields_preserved_with_three_additive_refinements=True,inherited_rules_context_prefix_preserved=True,semantic_node_rule_review=NOTE+' §8',joint_premise_review=NOTE+' §§3–5',internal_external_sort_audit='No h(c) for external c; only internal r,k enter theta_frame',quantitative_independence_not_inferred=True,no_report_to_F_or_C1_rule=True,no_global_semantic_certification=True,direction_checks=['PASS_AFTER_SELECTION','PASS_AFTER_RESULT','PASS_BEFORE_SAVE']))
entries=[
 ('R159-G1','REPAIRED_TYPING_OPEN_REALIZATION','R158 bearer/candidate contract and applications of R157 internal selector','R158:TARGET_SPLIT; R157:DEFINABLE_SELECTOR_SETUP; R159 frame application','External c outside D(P) makes h(c) undefined.','Add internal k and reference psi; transport r,k only.','Reference grounding and any expanded environmental signature remain independent.'),
 ('R159-G2','CLARIFIED_SCOPE','Reading qualitative ownership/agency distinction as quantitative independence','R158 profile and candidate fit claims','Coupled exact o/q family dissociates by sign but has positive cross-effects.','Explicit coupled-role family; no isolated-channel law inferred.','Physiological role measurements and causal cross-modulation architecture not identified.'),
 ('R159-G3','OPEN','Body-frame binding versus external-tool tracking','R159:ANCHOR_BINDING_CONTRACT / SELECTED_OWNERSHIP_APPLICATION','An externally interpreted tracking token could be called a body slot without actual body-specific sensitivity.','Require independent physical relational witness and specified consumers; no label-based installation.','Actual body-slot/tool-slot discriminant not established by the four condition bits.'),
 ('R159-G4','OPEN','Specific F_O application and report bridge','R159 selected ownership; all phenomenal extrapolation','Role model and report fit can coexist with ungrounded familiar-label interpretation.','C1 structural application separate from fixed B_min/measurement; error not absence.','Independent selected target and nonreport measurement remain open.'),
 ('R159-G5','OPEN','Within-participant intervention and complete actual organization','Actual application of all new clauses','Same participant at different trials is not same P,I or complete neural K.','Trial-indexed tokens and fixed lineage; mechanical coupling does not imply unique owner.','Complete physical realization, histories and jointly admissible neural perturbations unresolved.'),
 ('R159-G6','DECLARED_EVIDENCE_BOUNDARY','Neural novelty and empirical source scope','Prior-art comparisons and data claims','Robot drift model does not establish subjective ownership; unavailable full text not full review.','Primary protocol windows and robot abstract scope recorded; no neural fit/experiment/priority claim.','Independent peer validation and broader prior-art review not completed.')]
save('GAP_LEDGER.json',dict(inherited='records/R158_Body_Ownership_Agency_Ablation_20261007/GAP_LEDGER.json',closed_inherited_families=[],entries=[dict(id=i,status=s,location=l,affected=a,counterexample=c,repaired=r,unresolved=u) for i,s,l,a,c,r,u in entries]))
save('SOURCE_LEDGER.json',dict(date='2026-10-07',fixed_A_sha256='2e4469afbd1d1862463cc36396dd6e2b50c418f22d6f0fd584bbae33bfedc6f4',fixed_read_scope='UCT I v1.2 §§8.11–8.14,14.7–14.10 targeted windows; R158 §§2,5–8; current entrypoints',source_hashes='VALIDATION.json all ten; not all papers reread',sources=[dict(id='S1',doi='10.3389/fnhum.2012.00040',url='https://www.frontiersin.org/journals/human-neuroscience/articles/10.3389/fnhum.2012.00040/full',scope='Publisher apparatus/conditions/questionnaire, experiment 3 qualitative/graded results; no raw reanalysis'),dict(id='S2',url='https://arxiv.org/abs/1806.06809v2',scope='Abstract only, prior body-estimation-model boundary; not full methods review')],failed_retrievals=[dict(source='NCBI PMC3303087 / PubMed15709864',outcome='Bot check/incomplete page; no full-text claims from these responses',recovery='Publisher 2012 protocol used; Tsakiris/Haggard 2005 not relied on'),dict(source='Broad system1 query for 2005 paper',outcome='Returned unrelated results; discarded, not used as evidence')],new_neural_mechanism_claim=False,raw_data_analysis=False,priority_search_complete=False))
save('PROOF_LEDGER.json',dict(source=NOTE,claims=[dict(id=x['id'],type=x['kind'],statement=x['statement'],scope=x['scope'],quantifiers=x['formal_contract_R159']['quantifiers'],all_of_routes=x['formal_contract_R159']['premise_routes'],argument=x['proof'],limits=x['counterexamples_and_limits'],status=x['status'],thought_experiments=NOTE+' §7') for x in nodes],note='Only one conditional application rule; definitions, a concrete algebraic witness and an open bridge are not counted as proved physiological theorems.'))
print(json.dumps(dict(status='PASS',nodes=len(ids),rules=len(rid),new_nodes=4,new_rules=1)))
