#!/usr/bin/env python3
import hashlib
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
GRAPH = ROOT / "UCT_FORMAL_GRAPH.json"
PARENT_REV = "R174-BR20261008-v1.0"
REV = "R175-v1.0"


def sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def write(path, obj):
    path.write_text(json.dumps(obj, indent=2, ensure_ascii=False) + "\n")


def node(i, statement, kind, status, limits):
    return {"id": i, "statement": statement, "kind": kind, "domain": "One declared actual bearer/token/episode unless explicitly a finite alternative-model class.", "quantifiers": "Only the quantifiers displayed in the R175 note; no universal biological or phenomenal generalization.", "actuality": "Actuality requires independent grounding; abstract models and evidence records do not install the relation.", "status": status, "source": "records/R175_Oriented_Temporal_Order_20261008/Oriented_Temporal_Order_and_Held_Out_Content_v0_1.md", "limits": limits}


def main():
    graph = json.loads(GRAPH.read_text())
    assert graph["revision"] == PARENT_REV
    parent_counts = (len(graph["nodes"]), len(graph["rules"]), len(graph["context_links"]))
    assert parent_counts == (554, 267, 168)
    note = HERE / "Oriented_Temporal_Order_and_Held_Out_Content_v0_1.md"
    model = HERE / "MODEL_RESULTS.json"
    note_hash, model_hash = sha(note), sha(model)

    nodes = [
      node("R175:BASELINE_ADMITTED_ACTION_DOMAIN", "The actual baseline trajectory belongs to the operation family used by Avail; on this domain an actual same-episode AgencyLoop contains an admitted action occurrence and therefore implies Avail.", "EFFECTIVE_DOMAIN_CONTRACT", "DECLARED_SCOPE_CORRECTION", "Other availability conventions require separate disclosure."),
      node("R175:SIX_ROW_EVENT_MODELS", "Under baseline admission, exactly six A/G/R rows remain; explicit event-role models realize no-loop, available-no-loop and admitted agency-loop cases, each with RetBind absent or present.", "FINITE_SEMANTIC_WITNESS_CLASS", "EXACT_CONSTRUCTION_ON_DECLARED_DOMAIN", "Not empirical prevalence or eight-way independence."),
      node("R175:EXPLICIT_TWIN_DOMAIN", "The comparison domain explicitly contains two alternative histories with identical present descriptors and different actual provenance/use paths.", "APPLICATION_PREMISE", "DECLARED_REQUIRED_PREMISE", "Not entailed by predicate definitions or one positive instance."),
      node("R175:ADMITTED_HISTORY_TWIN", "Given the explicit twin-domain premise, the same-present/different-history pair is admitted and can support the conditional present-slice nonentailment proof.", "CORRECTED_COUNTERMODEL_INSTANCE", "CONDITIONAL_EXACT_WITNESS", "No phenomenal difference assigned."),
      node("R175:R173_EFFECTIVE_TARGET_SEPARATION", "F_O, F_A and F_F remain separately fixed semantic targets; no eight-way organizational independence is asserted or needed for the familiar-mineness boundary.", "EFFECTIVE_SCOPE_CORRECTION", "CONDITIONAL_BOUNDARY", "Targets may overlap or be undefined."),
      node("R175:R174_FIBER_DIRECTION_CORRECTION", "Sufficiency fails when equal Theta_STC values admit different independently warranted F_order values; changed Theta_STC with invariant F_order addresses only a claimed sensitivity/injectivity direction.", "EFFECTIVE_EDITORIAL_INFERENCE_CORRECTION", "EXACT_LOGICAL_CORRECTION", "Does not close the empirical bridge."),
      node("R175:PHYSICAL_TEMPORAL_CHAIN", "Four actual physical events form an independently grounded strict order inside one Theta_STC-type route on one token and episode.", "ACTUAL_ORGANIZATIONAL_TARGET", "DECLARED_PENDING_ACTUAL_INSTANTIATION", "A model chain or report is insufficient."),
      node("R175:INDEPENDENT_EXPERIENTIAL_ORDER", "Four experiential relata and their before/betweenness structure are independently admitted for the same token, not generated by copying the physical chain.", "EXPERIENTIAL_INTERPRETATION_PREMISE", "OPEN_EMPIRICAL_SEMANTIC_ADMISSION", "Report may be fallible evidence but not target definition."),
      node("R175:BETWEENNESS_CORRESPONDENCE_CLASS", "For equal finite chains n>=3, the betweenness-preserving correspondence class contains exactly the increasing and decreasing maps, leaving one orientation bit.", "CLASSICAL_FINITE_THEOREM", "MANUAL_PROOF_AND_EXACT_CHECK", "Assumes one common map and independently fixed relation meanings."),
      node("R175:ORIENTATION_ANCHOR_PACKAGE", "Two common, independently admitted endpoint correspondences fix the same orientation and are frozen before the middle target is evaluated.", "JOINT_ANCHOR_PREMISE", "DECLARED_PENDING_EMPIRICAL_SUPPORT", "Separate per-anchor maps, switched tokens or fitted anchors do not qualify."),
      node("R175:HELD_OUT_ORDER_PREDICTION", "The common orientation package forces the increasing map and therefore the unfitted relation f(x1)<_E f(x2), while the reversal rival predicts the opposite.", "POSITIVE_HELD_OUT_CONTENT_CONSTRAINT", "MANUAL_PROOF_AND_EXACT_CHECK", "Conditional on all physical, experiential, common-map and anchor premises."),
      node("R175:B_ORDER_NARROWED_BOUNDARY", "R175 reduces the finite-chain B_order application to independent experiential admission and orientation anchoring, with explicit copied-structure, inconsistency and ambiguity failures; it does not close B_order generally.", "CONDITIONAL_EXPLANATORY_BOUNDARY", "POSITIVE_PROGRESS_WITH_OPEN_EMPIRICAL_BRIDGE", "No basal gate, unique owner or cross-trial identity follows.")
    ]

    rules = [
      {"id":"r175_r173_six_row_effective","all_of":["R175:BASELINE_ADMITTED_ACTION_DOMAIN","R173:CURRENT_ACTION_AVAILABILITY","R173:CURRENT_AGENCY_LOOP","R173:RETENTIVE_BINDING_RELATION"],"conclusion":"R175:SIX_ROW_EVENT_MODELS","kind":"EFFECTIVE_SCOPE_CORRECTION","statement":"Baseline admission and the typed relations jointly yield the six-row event-model class; G=1,A=0 is excluded.","source":str(note.relative_to(ROOT)),"proof":"Explicit event-role construction and G=>A.","source_sha256":note_hash},
      {"id":"r175_r173_history_twin_effective","all_of":["R175:EXPLICIT_TWIN_DOMAIN","R173:FIXED_FAMILIAR_TARGET_CONTRACT"],"conclusion":"R175:ADMITTED_HISTORY_TWIN","kind":"CORRECTED_CONDITIONAL_COUNTERMODEL","statement":"An explicit admitted twin-domain premise, not predicate definitions alone, supplies the comparison pair.","source":str(note.relative_to(ROOT)),"proof":"Direct use of the declared two-history domain.","source_sha256":note_hash},
      {"id":"r175_r173_target_boundary_effective","all_of":["R173:RETENTIVE_EXPERIENTIAL_COORDINATE","R175:R173_EFFECTIVE_TARGET_SEPARATION","R157:SEMANTIC_RESIDUAL"],"conclusion":"R173:FAMILIAR_MINENESS_BOUNDARY","kind":"EFFECTIVE_BOUNDARY_REPLACEMENT","statement":"The corrected familiar-mineness boundary needs target distinction and semantic residual, not eight-way organizational independence.","source":str(note.relative_to(ROOT)),"proof":"Scope correction; no new phenomenal assignment.","source_sha256":note_hash},
      {"id":"r175_betweenness_residual","all_of":["R175:PHYSICAL_TEMPORAL_CHAIN","R175:INDEPENDENT_EXPERIENTIAL_ORDER","BR20261008:JOINT_MAPPING_CONSTRAINT"],"conclusion":"R175:BETWEENNESS_CORRESPONDENCE_CLASS","kind":"CONDITIONAL_CLASSICAL_DEDUCTION","statement":"One common independently admitted betweenness correspondence leaves exactly increasing and decreasing rivals.","source":str(note.relative_to(ROOT)),"proof":"Endpoint and rank argument.","source_sha256":note_hash},
      {"id":"r175_orientation_forces_heldout","all_of":["R175:BETWEENNESS_CORRESPONDENCE_CLASS","R175:ORIENTATION_ANCHOR_PACKAGE"],"conclusion":"R175:HELD_OUT_ORDER_PREDICTION","kind":"POSITIVE_CONDITIONAL_DEDUCTION","statement":"Common oriented endpoint anchors select the increasing map and force the untouched middle relation.","source":str(note.relative_to(ROOT)),"proof":"Eliminate the reversal member of the two-map class.","source_sha256":note_hash},
      {"id":"r175_b_order_narrowed","all_of":["R175:HELD_OUT_ORDER_PREDICTION","R175:R174_FIBER_DIRECTION_CORRECTION","R174:B_ORDER_BOUNDARY","R157:SEMANTIC_RESIDUAL"],"conclusion":"R175:B_ORDER_NARROWED_BOUNDARY","kind":"CONDITIONAL_EXPLANATORY_BOUNDARY","statement":"The positive held-out constraint and corrected failure directions narrow but do not globally close B_order.","source":str(note.relative_to(ROOT)),"proof":"Held-out success is conditional; independent admission and residual semantics remain.","source_sha256":note_hash}
    ]
    links = [
      {"from":"R173:THREE_TARGET_SEPARATION","to":"R175:R173_EFFECTIVE_TARGET_SEPARATION","relation":"review_corrected_by","deductive":False},
      {"from":"R174:B_ORDER_BOUNDARY","to":"R175:R174_FIBER_DIRECTION_CORRECTION","relation":"failure_direction_corrected_by","deductive":False},
      {"from":"BR20261008:COMMON_EXPERIENTIAL_CONSTRAINT","to":"R175:HELD_OUT_ORDER_PREDICTION","relation":"instantiated_by","deductive":False},
      {"from":"R174:SHARED_TEMPORAL_COORDINATE","to":"R175:PHYSICAL_TEMPORAL_CHAIN","relation":"scoped_as","deductive":False},
      {"from":"R175:HELD_OUT_ORDER_PREDICTION","to":"R173:FAMILIAR_MINENESS_BOUNDARY","relation":"does_not_close","deductive":False}
    ]
    old_ids = {x["id"] for k in ("nodes","rules","context_links") for x in graph[k] if "id" in x}
    assert all(x["id"] not in old_ids for x in nodes + rules)
    graph["nodes"].extend(nodes); graph["rules"].extend(rules); graph["context_links"].extend(links)
    graph["revision"] = REV
    write(GRAPH, graph)

    amendments = {
      "review":"REVIEW-20261008-03","response":"R175","status":"RESEARCHER_CORRECTION_PENDING_INDEPENDENT_REVIEW",
      "suspended_raw_rules":["r173_history_twin_witness","r173_familiar_mineness_boundary"],
      "effective_replacements":["r175_r173_six_row_effective","r175_r173_history_twin_effective","r175_r173_target_boundary_effective"],
      "qc08":{"accepted":True,"correction":"G=>A on baseline-admitted domain; six semantic rows; explicit TwinDomain required; target distinction retained without eight-way independence."},
      "qc09":{"accepted":True,"correction":"Same Theta_STC/different F_order refutes sufficiency; changed Theta_STC/same F_order only refutes a sensitivity/injectivity claim."},
      "qc10":{"response":"R175 positive conditional held-out temporal-order prediction with independent structures, common map, reversal rival and explicit failure criteria; empirical closure remains open."},
      "source_sha256":note_hash
    }
    write(HERE / "REVIEW_AMENDMENTS.json", amendments)
    ext = {"revision":REV,"parent_revision":PARENT_REV,"new_nodes":nodes,"new_rules":rules,"new_context_links":links,"review_overlay":"REVIEW_AMENDMENTS.json"}
    write(HERE / "MAP_EXTENSION.json", ext)
    checks = [
      ("exact_parent_counts", parent_counts == (554,267,168)),
      ("exact_new_counts", (len(nodes),len(rules),len(links)) == (12,6,5)),
      ("unique_ids", len({x["id"] for x in graph["nodes"]}) == len(graph["nodes"]) and len({x["id"] for x in graph["rules"]}) == len(graph["rules"])),
      ("all_rule_endpoints", all(all(p in {n["id"] for n in graph["nodes"]} for p in r["all_of"]+[r["conclusion"]]) for r in graph["rules"])),
      ("note_hash", sha(note)==note_hash),("model_hash",sha(model)==model_hash),
      ("model_12", json.loads(model.read_text())["checks_passed"]==12),
      ("qc08_twin_explicit", "R175:EXPLICIT_TWIN_DOMAIN" in rules[1]["all_of"]),
      ("qc09_direction_split", "sufficiency" in nodes[5]["statement"].lower() and "sensitivity" in nodes[5]["statement"].lower()),
      ("independent_experience_premise", "independently" in nodes[7]["statement"]),
      ("one_common_map", "one common" in rules[3]["statement"].lower()),
      ("heldout_not_anchor", "untouched" in rules[4]["statement"]),
      ("semantic_residual_retained", "R157:SEMANTIC_RESIDUAL" in rules[5]["all_of"]),
      ("no_report_gate", "report" not in rules[4]["all_of"]),
      ("counts", (len(graph["nodes"]),len(graph["rules"]),len(graph["context_links"]))==(566,273,173))
    ]
    if not all(v for _,v in checks):
        raise AssertionError([n for n, v in checks if not v])
    audit={"revision":REV,"counts":{"nodes":len(graph["nodes"]),"rules":len(graph["rules"]),"context_links":len(graph["context_links"])},"checks":[{"name":n,"pass":v} for n,v in checks],"scope":"Structural and scoped semantic audit; not empirical validation, C1 proof or global theory proof.","graph_sha256":sha(GRAPH),"note_sha256":note_hash,"model_sha256":model_hash}
    write(HERE / "MAP_AUDIT.json", audit)
    proof={"round":"R175","items":[
      {"id":"R175-A","claim":"Finite-chain betweenness maps are exactly increasing or decreasing.","premises":["equal finite strict chains n>=3","bijection preserves and reflects betweenness"],"proof":"Endpoint/rank proof in §3","counterexample_boundary":"Without chain/betweenness assumptions other maps may exist.","status":"PROVED_ON_DECLARED_CLASS"},
      {"id":"R175-B","claim":"Common oriented endpoint anchors force the held-out middle experienced-order relation.","premises":["R175-A","one common same-token map","independent endpoint anchors","held-out relation not fitted"],"proof":"Reversal elimination in §4","counterexample_boundary":"No anchors leaves two rivals; incompatible anchors leave no map.","status":"PROVED_CONDITIONALLY"},
      {"id":"R175-C","claim":"QC-08 eight-way wording is unsupported on the baseline-admitted domain.","premises":["baseline trajectory admitted","AgencyLoop contains actual action production"],"proof":"G=>A; explicit six-row models","counterexample_boundary":"Other Avail conventions must be separately declared.","status":"EFFECTIVE_SCOPE_CORRECTION_PENDING_REVIEW"}
    ]}
    write(HERE / "PROOF_LEDGER.json", proof)
    sources={"round":"R175","items":[
      {"id":"S1","source":"UCT A/I v1.2 and R157","use":"C1 transport and semantic residual","scope":"Pinned internal primary theory source."},
      {"id":"S2","source":"R173/R174/BR20261008 and REVIEW-20261008-03","use":"Target contracts, route boundary, joint-map theorem and review corrections","scope":"Exact saved repository sources."},
      {"id":"S3","source":"Kleiner 2024, Consciousness and Cognition 119:103653","use":"Independent phenomenal-structure and bare-isomorphism challenge","scope":"As pinned/read in BR20261008; not evidence for C1."},
      {"id":"S4","source":"Aldé 2026, Synthese 207:204","use":"Similarity geometry does not by itself fix specific phenomenal content","scope":"As pinned/read in BR20261008; not a temporal-order experiment."}
    ],"novelty":"Classical finite-order mathematics is not claimed new; project contribution is typed integration and held-out criterion."}
    write(HERE / "SOURCE_LEDGER.json", sources)
    gaps={"round":"R175","record_type":"RESEARCH_SELF_CHECK_NOT_INDEPENDENT_REVIEW","items":[
      {"id":"R175-G1","severity":"HIGH","location":"§2 experiential admission","impact":"Blocks actual B_order application.","counterexample":"E is copied from the physical chain or defined by the report used as outcome.","repaired":"Independence firewall and pre-registration requirement.","unresolved":"No actual independently grounded same-token experiential chain.","status":"OPEN"},
      {"id":"R175-G2","severity":"HIGH","location":"§2 physical chain","impact":"Blocks actual route grounding.","counterexample":"Stored timestamps or correct answers without executed shared comparison/use.","repaired":"Requires one actual Theta_STC-type route and nonreport consumer.","unresolved":"No actual human/hardware path instance.","status":"OPEN"},
      {"id":"R175-G3","severity":"HIGH","location":"§4 anchors","impact":"Can make the held-out prediction circular.","counterexample":"Endpoint anchors are chosen after seeing the middle target or from different tokens.","repaired":"Common-map, frozen-anchor and held-out clauses.","unresolved":"No implemented blinded protocol.","status":"OPEN"},
      {"id":"R175-G4","severity":"MEDIUM","location":"§3 relation choice","impact":"Betweenness may be too weak or wrong for actual experienced time.","counterexample":"Nonlinear, cyclic or incomparable experiential temporal structure.","repaired":"No generalization beyond the admitted finite chain.","unresolved":"Appropriate experiential relation remains empirical/phenomenological.","status":"OPEN"},
      {"id":"R175-G5","severity":"HIGH","location":"QC-08--10","impact":"Reviewer closure and empirical content remain unavailable.","counterexample":"Self-declared PASS cannot close QC items.","repaired":"Explicit response, overlay and conditional positive prediction.","unresolved":"QC-08/09/10 await independent reviewer assessment.","status":"OPEN"},
      {"id":"R175-G6","severity":"MEDIUM","location":"C1 attachment","impact":"Selected mapping may not extend to the complete K-isomorphism.","counterexample":"Unique selected map conflicts with omitted complete relations.","repaired":"Actual restriction and extension premise retained.","unresolved":"No complete actual instance.","status":"OPEN"}
    ]}
    write(HERE / "GAP_LEDGER.json", gaps)
    print(json.dumps({"revision":REV,"counts":audit["counts"],"checks":len(checks),"graph_sha256":audit["graph_sha256"]}))


if __name__ == "__main__":
    main()
