#!/usr/bin/env python3
"""Exhaustive Boolean audit of a minimal phenomenal-anchor candidate."""

import itertools
import json
from pathlib import Path

DOMAIN = tuple(itertools.product((0, 1), repeat=3))  # F, S, K


def bit(mask, index):
    return (mask >> index) & 1


def value(mask, f, s, k):
    return bit(mask, DOMAIN.index((f, s, k)))


survivors = []
defeats = {"code": 0, "source": 0, "formation": 0}
for mask in range(1 << len(DOMAIN)):
    corrected = {(f, s, k): value(mask, f, s, k) ^ k for f, s, k in DOMAIN}
    code_ok = all(corrected[f, s, 0] == corrected[f, s, 1] for f, s in itertools.product((0, 1), repeat=2))
    source_ok = all(corrected[f, 0, k] == corrected[f, 1, k] for f, k in itertools.product((0, 1), repeat=2))
    formation_sensitive = all(corrected[0, s, k] != corrected[1, s, k] for s, k in itertools.product((0, 1), repeat=2))
    defeats["code"] += not code_ok
    defeats["source"] += not source_ok
    defeats["formation"] += not formation_sensitive
    if code_ok and source_ok and formation_sensitive:
        survivors.append({"mask": mask, "truth_table": "".join(str(value(mask, *x)) for x in DOMAIN)})

assert len(survivors) == 2

# Both surviving corrected reports can be generated by a nonphenomenal proxy W=F.
# H is unconstrained and may equal F, be constant, or equal 1-F without changing R.
proxy_models = {
    "aligned": {"H": "F", "W": "F"},
    "independent_constant": {"H": "0", "W": "F"},
    "opposed": {"H": "1-F", "W": "F"},
}

result = {
    "schema": "uct-a3z-anchor-triage-exact-v1",
    "status": "PASS_EXHAUSTIVE_BOOLEAN_WITNESS",
    "functions_enumerated": 256,
    "requirements": {
        "code_invariance": "R=J xor K is invariant under response-key K",
        "source_invariance": "R is invariant under nuisance source/agency label S",
        "formation_sensitivity": "R flips under candidate formation/history contrast F"
    },
    "survivor_count": len(survivors),
    "survivors": survivors,
    "proxy_only_models_with_same_observables": proxy_models,
    "interpretive_ceiling": "Violations reject the declared bridge package; satisfaction leaves both polarity and H_way identity unidentified."
}
Path(__file__).with_name("EXACT_RESULTS.json").write_text(
    json.dumps(result, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8"
)
print(json.dumps(result, ensure_ascii=False, sort_keys=True))
