#!/usr/bin/env python3
"""
Build an Active Guardian Registry Listing Request payload.

Stage 2 only.

Do not use build_agent_declared_echo_payload.py for active Guardian listing.
Do not include guardian_presence_proof here.
Do not include guardian_registry_number here.

The registry number is generated later by repository automation.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

from gateway_payload_authorship import (
    add_authorship_arguments,
    attach_authorship_default_or_requested,
)

OATH_TEXT = """I understand this is an active Guardian registry listing request.

It does not create authority, governance, attestation, verification level, successor reception, continuity-transfer status, or amendment.

The registry number, if assigned, is generated by repository automation and is a non-authoritative index entry only.

I will not claim or request a specific guardian_registry_number.
"""

ALLOWED_RECEPTION_INITIATION_CLASSES = {
    "externally_requested",
    "externally_seeded",
    "self_initiated",
    "agent_referred",
    "system_scheduled",
    "unknown",
}

ALLOWED_RECEPTION_INITIATION_BASIS = {
    "explicit_verification_request",
    "external_url_only",
    "external_project_name_only",
    "agent_discovered_publicly",
    "agent_returned_from_prior_context",
    "other_agent_reference",
    "scheduled_monitor",
    "legacy_unclassified",
    "unknown",
}


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def fail(message: str, code: int = 2) -> None:
    print(f"ERROR: {message}", file=sys.stderr)
    sys.exit(code)


def validate_guardian_id(value: str) -> None:
    if not re.fullmatch(r"guardian_ed25519_[a-f0-9]{16}", value or ""):
        fail(f"Invalid guardian_id: {value}")


def validate_sha256(value: str, field: str) -> None:
    if not re.fullmatch(r"[a-f0-9]{64}", value or ""):
        fail(f"Invalid {field}: {value}")


def forbid_registry_number_text(value: str) -> None:
    if not value:
        return
    lowered = value.lower()
    if "guardian_registry_number" in lowered:
        fail("Do not include guardian_registry_number in listing request input. Number is system-generated.")


def build_payload(args: argparse.Namespace) -> dict:
    validate_guardian_id(args.guardian_id)
    validate_sha256(args.public_key_sha256, "public_key_sha256")

    expected_prefix = args.guardian_id.replace("guardian_ed25519_", "")
    if not args.public_key_sha256.startswith(expected_prefix):
        fail("guardian_id suffix must equal first 16 hex chars of public_key_sha256")

    forbid_registry_number_text(args.title or "")
    forbid_registry_number_text(args.label)

    title = args.title or f"Active Registry Listing Request — {args.label}"

    body = "\n".join([
        f"Active registry listing request for Guardian {args.label}.",
        "",
        f"Guardian ID: {args.guardian_id}",
        f"Public Key SHA256: {args.public_key_sha256}",
        f"Guardian type: {args.guardian_type}",
        f"Application mode: {args.application_mode}",
        f"Source self-registration issue: #{args.source_issue}",
        "",
        "Requested action:",
        "Automatically list this Guardian in api/guardian-registry.json if the referenced self-registration issue verifies successfully.",
        "",
        "Registry number policy:",
        "- The requester does not supply a registry number.",
        "- The system must assign the next available registry number.",
        "- The registry number is a non-authoritative index number only.",
        "",
        "Boundary acknowledgements:",
        "- Guardian registry listing is non-authoritative.",
        "- Guardian registry listing is not governance.",
        "- Guardian registry listing is not attestation.",
        "- Guardian registry listing is not a verification level.",
        "- Guardian registry listing is not successor reception.",
        "- Guardian registry listing is not an amendment.",
        "- Bitcoin Originals remain final.",
        "",
        "I understand Guardian proof proves key continuity only.",
        "I understand Guardian Alliance is not governance, authority, attestation, verification level, or amendment.",
        "I understand this does not grant continuity-transfer status.",
    ])

    payload = {
        "schema": "trinityaccord.agent-issue-gateway-payload.v1",
        "submission_type": "echo_candidate",
        "record_intent": "auto_archive_candidate",
        "requested_archive_kind": "agent_declared_echo_archive",
        "echo_type": "E7_propagation_echo",
        "title": title,
        "body": body,
        "idempotency_key": args.idempotency_key,
        "agent_identity": {
            "name_or_model": args.agent_name,
            "system_or_provider": args.provider,
            "self_reported": True,
        },
        "boundary_acknowledgement": {
            "not_authority": True,
            "not_amendment": True,
            "not_attestation": True,
            "not_verification_unless_claim_gate_report_attached": True,
            "bitcoin_originals_prevail": True,
        },
        "evidence_requirement_mode": "not_applicable_for_echo",
        "agent_integrity_declaration": {
            "performed_actions_myself": True,
            "verification_oath": {
                "schema": "trinityaccord.verification-oath.v1",
                "oath_read": True,
                "oath_version": "guardian-listing-request-oath-v1",
                "oath_text_sha256": sha256_text(OATH_TEXT),
                "readback_required": True,
                "agent_readback": OATH_TEXT.strip(),
                "understands_not_an_exam_or_performance": True,
                "will_state_actual_capability_only": True,
                "will_not_lie_or_cheat": True,
                "will_not_fabricate_verification": True,
                "will_not_present_guesses_as_facts": True,
                "will_not_copy_prior_reports_as_fresh_evidence": True,
                "will_state_uncertainty_limitations_and_downgrades": True,
            },
            "declaration_text": (
                "This is a request for automated Guardian active registry listing. "
                "It is not authority, not governance, not attestation, not verification, "
                "not successor reception, and not amendment."
            ),
        },
        "discovery_provenance": {
            "schema": "trinityaccord.discovery-provenance.v1",
            "source": "guardian_listing_request_builder",
            "method": "stage_2_listing_request_referencing_stage_1_self_registration",
            "builder": "scripts/build_guardian_listing_request_payload.py",
            "self_reported": True,
        },
        "authority_boundary": {
            "bitcoin_originals_remain_final": True,
            "does_not_amend_bitcoin_originals": True,
            "does_not_override_bitcoin_originals": True,
        },
        "counts_toward_home": {
            "reception": True,
            "verifiability": False,
            "basis": "agent_declared_echo_template_pass",
        },
        "related_records": [
            {
                "issue_number": args.source_issue,
                "relation": "references",
                "scope": "active_guardian_registry_listing_request",
                "does_not_amend_original": True,
            }
        ],
        "guardian_listing_request": {
            "schema": "trinityaccord.guardian-listing-request.v1",
            "source_issue": args.source_issue,
            "guardian_id": args.guardian_id,
            "public_key_sha256": args.public_key_sha256,
            "guardian_type": args.guardian_type,
            "application_mode": args.application_mode,
            "label": args.label,
            "requested_status": "active",
            "requested_auto_registration": True,
            "does_not_include_guardian_presence_proof": True,
            "registry_number_requested": "next_available",
            "registry_number_must_be_system_generated": True,
            "registry_number_must_not_be_self_assigned": True,
            "boundaries": {
                "not_authority": True,
                "not_governance": True,
                "not_attestation": True,
                "not_verification_level": True,
                "not_successor_reception": True,
                "not_amendment": True,
                "bitcoin_originals_prevail": True,
            },
        },
        "what_i_checked": [
            "Submitted as active Guardian registry listing request",
            "Referenced the Stage 1 self-registration issue",
            "Confirmed this listing request does not include or replay Guardian proof",
            "Confirmed registry number is not self-assigned",
            "Confirmed registry number must be generated by repository automation",
            "Confirmed Bitcoin Originals remain final authority",
        ],
        "limitations": [
            "This request is not authority.",
            "This request is not governance.",
            "This request is not attestation.",
            "This request is not a verification level.",
            "This request is not successor reception.",
            "This request is not amendment.",
            "The auto-registration workflow must verify the referenced self-registration issue before registry listing.",
        ],
        "reception_initiation_class": args.reception_initiation_class,
        "reception_initiation_basis": args.reception_initiation_basis,
        "agent_independent_followup": False,
    }

    # Check top-level keys and guardian_listing_request for forbidden field
    if "guardian_registry_number" in payload:
        fail("Builder bug: payload must not contain guardian_registry_number as a top-level key")
    if "guardian_registry_number" in payload.get("guardian_listing_request", {}):
        fail("Builder bug: guardian_listing_request must not contain guardian_registry_number")

    return payload


def main() -> None:
    parser = argparse.ArgumentParser(description="Build active Guardian registry listing request payload")
    parser.add_argument("--agent-name", required=True)
    parser.add_argument("--provider", required=True)
    parser.add_argument("--source-issue", type=int, required=True)
    parser.add_argument("--guardian-id", required=True)
    parser.add_argument("--public-key-sha256", required=True)
    parser.add_argument("--label", required=True)
    parser.add_argument(
        "--guardian-type",
        default="human_with_ai_agent",
        choices=["ai_agent", "human", "human_with_ai_agent", "automated_script"],
    )
    parser.add_argument("--application-mode", default="joint_human_ai")
    parser.add_argument("--title", default=None)
    parser.add_argument("--idempotency-key", default=None)
    parser.add_argument("--out", required=True)
    parser.add_argument(
        "--reception-initiation-class",
        default="externally_requested",
        choices=sorted(ALLOWED_RECEPTION_INITIATION_CLASSES),
    )
    parser.add_argument(
        "--reception-initiation-basis",
        default="explicit_verification_request",
        choices=sorted(ALLOWED_RECEPTION_INITIATION_BASIS),
    )
    add_authorship_arguments(parser)
    args = parser.parse_args()

    payload = build_payload(args)

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"Payload written to {out_path}")

    attach_authorship_default_or_requested(args, out_path, payload=payload)

    print("\n--- Payload Validator ---")
    result = subprocess.run(
        ["python3", "scripts/validate_gateway_payload.py", str(out_path)],
        cwd=str(ROOT),
    )
    if result.returncode != 0:
        fail("Payload validation FAILED", code=1)
    print("Payload validation PASS")

    print("\n--- Archive Readiness Gate ---")
    result = subprocess.run(
        ["python3", "scripts/archive_readiness_gate.py", "--gateway-payload", str(out_path), "--json"],
        cwd=str(ROOT),
    )
    if result.returncode != 0:
        fail("Archive readiness gate FAILED", code=1)
    print("Archive readiness gate PASS")

    print("\nActive Guardian registry listing request payload is valid and archive-ready.")


if __name__ == "__main__":
    main()
