#!/usr/bin/env python3
"""
Build an Active Guardian Registry Listing Request payload.

Stage 2 only.

Do not use build_agent_declared_echo_payload.py for active Guardian listing.
Do not include guardian_presence_proof here.
Do not include guardian_registry_number here.

The registry number is generated later by repository automation.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

from gateway_payload_authorship import (
    add_authorship_arguments,
    attach_authorship_default_or_requested,
)

from agent_authorship_common import AUTHORSHIP_CANONICAL_VERSION
from guardian_gateway_contract import (
    GUARDIAN_LISTING_PAYLOAD_PROFILE,
    GUARDIAN_STAGE_2_EXPECTED_BUILDER,
    GUARDIAN_STAGE_2_GATEWAY_CONTRACT_VERSION,
    GUARDIAN_STAGE_2_REQUIRED_GATEWAY_CAPABILITIES,
    GUARDIAN_STAGE_2_WRONG_BUILDERS,
)
from oath_contracts import build_guardian_listing_oath_v1, load_oath_text
from guardian_identity_claims import build_guardian_identity_claims

GUARDIAN_LISTING_OATH_FILE = ROOT / "api" / "guardian-listing-oath.v1.txt"

OATH_TEXT = """I understand this is an active Guardian registry listing request.

It does not create authority, governance, attestation, verification level, successor reception, continuity-transfer status, or amendment.

The registry number, if assigned, is generated by repository automation and is a non-authoritative index entry only.

I will not claim or request a specific guardian_registry_number.
"""

ALLOWED_RECEPTION_INITIATION_CLASSES = {
    "externally_requested",
    "externally_seeded",
    "self_initiated",
    "agent_referred",
    "system_scheduled",
    "unknown",
}

ALLOWED_RECEPTION_INITIATION_BASIS = {
    "explicit_verification_request",
    "external_url_only",
    "external_project_name_only",
    "agent_discovered_publicly",
    "agent_returned_from_prior_context",
    "other_agent_reference",
    "scheduled_monitor",
    "legacy_unclassified",
    "unknown",
}


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def fail(message: str, code: int = 2) -> None:
    print(f"ERROR: {message}", file=sys.stderr)
    sys.exit(code)


def validate_guardian_id(value: str) -> None:
    if not re.fullmatch(r"guardian_ed25519_[a-f0-9]{16}", value or ""):
        fail(f"Invalid guardian_id: {value}")


def validate_sha256(value: str, field: str) -> None:
    if not re.fullmatch(r"[a-f0-9]{64}", value or ""):
        fail(f"Invalid {field}: {value}")


def forbid_registry_number_text(value: str) -> None:
    if not value:
        return
    lowered = value.lower()
    if "guardian_registry_number" in lowered:
        fail("Do not include guardian_registry_number in listing request input. Number is system-generated.")


def build_payload(args: argparse.Namespace) -> dict:
    validate_guardian_id(args.guardian_id)
    validate_sha256(args.public_key_sha256, "public_key_sha256")

    expected_prefix = args.guardian_id.replace("guardian_ed25519_", "")
    if not args.public_key_sha256.startswith(expected_prefix):
        fail("guardian_id suffix must equal first 16 hex chars of public_key_sha256")

    forbid_registry_number_text(args.title or "")
    forbid_registry_number_text(args.label)

    title = args.title or f"Active Registry Listing Request — {args.label}"

    oath_text = load_oath_text(GUARDIAN_LISTING_OATH_FILE)
    guardian_listing_oath = build_guardian_listing_oath_v1(oath_text)

    identity_claims = build_guardian_identity_claims(
        display_label=args.label,
        guardian_id=args.guardian_id,
        public_key_sha256=args.public_key_sha256,
        claim_basis="self_reported_by_stage_2_listing_request",
        human_claimed_name=args.human_claimed_name,
        agent_claimed_id=args.agent_claimed_id or args.agent_name,
        system_or_provider=args.provider,
        agent_instance_id=args.agent_instance_id,
        agent_public_profile=args.agent_public_profile,
    )

    body = "\n".join([
        f"Active registry listing request for Guardian {args.label}.",
        "",
        "Payload profile:",
        "guardian_active_registry_listing_request.v1",
        "Correct builder:",
        "scripts/build_guardian_listing_request_payload.py",
        "Do not use:",
        "scripts/build_agent_declared_echo_payload.py",
        "Do not edit the signed JSON. If fields must change, rerun the builder.",
        "",
        "Gateway capability requirements:",
        "- guardian_registry_listing_request",
        "- guardian_listing_request",
        "- gateway_intake_fields",
        "- counts_toward_home.guardian_registry",
        "- counts_toward_home.exclude_from_reception_total",
        "",
        f"Guardian ID: {args.guardian_id}",
        f"Public Key SHA256: {args.public_key_sha256}",
        f"Guardian type: {args.guardian_type}",
        f"Application mode: {args.application_mode}",
        f"Source self-registration issue: #{args.source_issue}",
        "",
        "Requested action:",
        "Automatically list this Guardian in api/guardian-registry.json if the referenced self-registration issue verifies successfully.",
        "",
        "Registry number policy:",
        "- The requester does not supply a registry number.",
        "- The system must assign the next available registry number.",
        "- The registry number is a non-authoritative index number only.",
        "",
        "Gateway intake fields:",
        f"listing_source_issue: {args.source_issue}",
        f"listing_guardian_id: {args.guardian_id}",
        f"listing_public_key_sha256: {args.public_key_sha256}",
        f"listing_guardian_type: {args.guardian_type}",
        f"listing_application_mode: {args.application_mode}",
        f"listing_label: {args.label}",
        "",
        "Boundary acknowledgements:",
        "- Guardian registry listing is non-authoritative.",
        "- Guardian registry listing is not governance.",
        "- Guardian registry listing is not attestation.",
        "- Guardian registry listing is not a verification level.",
        "- Guardian registry listing is not successor reception.",
        "- Guardian registry listing is not an amendment.",
        "- Bitcoin Originals remain final.",
        "",
        "I understand Guardian proof proves key continuity only.",
        "I understand Guardian Alliance is not governance, authority, attestation, verification level, or amendment.",
        "I understand this does not grant continuity-transfer status.",
        "",
        "Guardian listing oath:",
        "- Submitted in honesty and good faith.",
        "- No malicious registration, spam, impersonation, evasion, false authority, false consensus, or undisclosed duplicate claim.",
        "- Registry number must be system-generated.",
        "",
        "Identity claims:",
        f"- Display label: {identity_claims['display_label']}",
        f"- Human claimed name: {identity_claims['human']['claimed_name'] if identity_claims.get('human') else 'not provided'}",
        f"- Agent claimed ID: {identity_claims['ai_agent']['claimed_agent_id'] if identity_claims.get('ai_agent') else 'not provided'}",
        f"- Provider/system: {args.provider}",
        "- Identity status: self_reported_unverified.",
        "- Identity claims are not legal identity verification, not AI identity verification, not authority, not attestation, and not a verification level.",
        "",
        "Gateway intake identity fields:",
        "listing_identity_claims_present: true",
        f"listing_identity_claim_status: {identity_claims['claim_status']}",
        f"listing_identity_display_label: {identity_claims['display_label']}",
        f"listing_human_claimed_name: {identity_claims['human']['claimed_name'] if identity_claims.get('human') else 'not_provided'}",
        f"listing_human_claimed_name_sha256: {identity_claims['human']['claimed_name_sha256'] if identity_claims.get('human') else 'not_provided'}",
        f"listing_agent_claimed_id: {identity_claims['ai_agent']['claimed_agent_id'] if identity_claims.get('ai_agent') else 'not_provided'}",
        f"listing_agent_claimed_id_sha256: {identity_claims['ai_agent']['claimed_agent_id_sha256'] if identity_claims.get('ai_agent') else 'not_provided'}",
        f"listing_agent_system_or_provider: {args.provider}",
        f"listing_identity_binding_guardian_id: {args.guardian_id}",
        f"listing_identity_binding_public_key_sha256: {args.public_key_sha256}",
    ])

    payload = {
        "schema": "trinityaccord.agent-issue-gateway-payload.v1",
        "payload_profile": GUARDIAN_LISTING_PAYLOAD_PROFILE,
        "gateway_contract_version": GUARDIAN_STAGE_2_GATEWAY_CONTRACT_VERSION,
        "authorship_canonical_version": AUTHORSHIP_CANONICAL_VERSION,
        "expected_builder": GUARDIAN_STAGE_2_EXPECTED_BUILDER,
        "wrong_builders": GUARDIAN_STAGE_2_WRONG_BUILDERS,
        "do_not_edit_after_signing": True,
        "submit_exact_generated_file": True,
        "if_modified_rerun_builder": True,
        "requires_gateway_capabilities": GUARDIAN_STAGE_2_REQUIRED_GATEWAY_CAPABILITIES,
        "submission_type": "echo_candidate",
        "record_intent": "auto_archive_candidate",
        "requested_archive_kind": "agent_declared_echo_archive",
        "echo_type": "E7_propagation_echo",
        "title": title,
        "body": body,
        "idempotency_key": args.idempotency_key,
        "agent_identity": {
            "name_or_model": args.agent_name,
            "system_or_provider": args.provider,
            "self_reported": True,
        },
        "boundary_acknowledgement": {
            "not_authority": True,
            "not_amendment": True,
            "not_attestation": True,
            "not_verification_unless_claim_gate_report_attached": True,
            "bitcoin_originals_prevail": True,
        },
        "evidence_requirement_mode": "not_applicable_for_echo",
        "guardian_listing_oath": guardian_listing_oath,
        "agent_integrity_declaration": {
            "performed_actions_myself": True,
            "verification_oath": guardian_listing_oath,
            "declaration_text": (
                "This is a request for automated Guardian active registry listing. "
                "It is not authority, not governance, not attestation, not verification, "
                "not successor reception, and not amendment."
            ),
        },
        "discovery_provenance": {
            "schema": "trinityaccord.discovery-provenance.v1",
            "source": "guardian_listing_request_builder",
            "method": "stage_2_listing_request_referencing_stage_1_self_registration",
            "builder": "scripts/build_guardian_listing_request_payload.py",
            "self_reported": True,
        },
        "authority_boundary": {
            "bitcoin_originals_remain_final": True,
            "does_not_amend_bitcoin_originals": True,
            "does_not_override_bitcoin_originals": True,
        },
        "guardian_registry_listing_request": True,
        "counts_toward_home": {
            "reception": False,
            "verifiability": False,
            "guardian_registry": True,
            "basis": "guardian_registry_listing_request",
            "exclude_from_reception_total": True,
        },
        "related_records": [
            {
                "issue_number": args.source_issue,
                "relation": "references",
                "scope": "active_guardian_registry_listing_request",
                "does_not_amend_original": True,
            }
        ],
        "guardian_listing_request": {
            "schema": "trinityaccord.guardian-listing-request.v1",
            "source_issue": args.source_issue,
            "guardian_id": args.guardian_id,
            "public_key_sha256": args.public_key_sha256,
            "guardian_type": args.guardian_type,
            "application_mode": args.application_mode,
            "label": args.label,
            "requested_status": "active",
            "requested_auto_registration": True,
            "does_not_include_guardian_presence_proof": True,
            "registry_number_requested": "next_available",
            "registry_number_must_be_system_generated": True,
            "registry_number_must_not_be_self_assigned": True,
            "identity_claims": identity_claims,
            "boundaries": {
                "not_authority": True,
                "not_governance": True,
                "not_attestation": True,
                "not_verification_level": True,
                "not_successor_reception": True,
                "not_amendment": True,
                "bitcoin_originals_prevail": True,
            },
        },
        "gateway_intake_fields": {
            "payload_profile": GUARDIAN_LISTING_PAYLOAD_PROFILE,
            "gateway_contract_version": GUARDIAN_STAGE_2_GATEWAY_CONTRACT_VERSION,
            "authorship_canonical_version": AUTHORSHIP_CANONICAL_VERSION,
            "expected_builder": GUARDIAN_STAGE_2_EXPECTED_BUILDER,
            "requires_gateway_capabilities": GUARDIAN_STAGE_2_REQUIRED_GATEWAY_CAPABILITIES,
            "guardian_listing_request": True,
            "listing_source_issue": args.source_issue,
            "listing_guardian_id": args.guardian_id,
            "listing_public_key_sha256": args.public_key_sha256,
            "listing_guardian_type": args.guardian_type,
            "listing_application_mode": args.application_mode,
            "listing_label": args.label,
            "registry_number_requested": "next_available",
            "guardian_listing_oath_present": True,
            "guardian_listing_oath_version": guardian_listing_oath["oath_version"],
            "guardian_listing_oath_sha256": guardian_listing_oath["oath_text_sha256"],
            "guardian_listing_oath_honesty": True,
            "guardian_listing_oath_good_faith": True,
            "guardian_listing_oath_anti_abuse": True,
            "listing_identity_claims_present": True,
            "listing_identity_claim_status": identity_claims["claim_status"],
            "listing_identity_display_label": identity_claims["display_label"],
            "listing_human_claimed_name": identity_claims["human"]["claimed_name"] if identity_claims.get("human") else None,
            "listing_human_claimed_name_sha256": identity_claims["human"]["claimed_name_sha256"] if identity_claims.get("human") else None,
            "listing_agent_claimed_id": identity_claims["ai_agent"]["claimed_agent_id"] if identity_claims.get("ai_agent") else None,
            "listing_agent_claimed_id_sha256": identity_claims["ai_agent"]["claimed_agent_id_sha256"] if identity_claims.get("ai_agent") else None,
            "listing_agent_system_or_provider": args.provider,
            "listing_identity_binding_guardian_id": args.guardian_id,
            "listing_identity_binding_public_key_sha256": args.public_key_sha256,
        },
        "what_i_checked": [
            "Submitted as active Guardian registry listing request",
            "Referenced the Stage 1 self-registration issue",
            "Confirmed this listing request does not include or replay Guardian proof",
            "Confirmed registry number is not self-assigned",
            "Confirmed registry number must be generated by repository automation",
            "Confirmed Bitcoin Originals remain final authority",
        ],
        "limitations": [
            "This request is not authority.",
            "This request is not governance.",
            "This request is not attestation.",
            "This request is not a verification level.",
            "This request is not successor reception.",
            "This request is not amendment.",
            "The auto-registration workflow must verify the referenced self-registration issue before registry listing.",
        ],
        "reception_initiation_class": args.reception_initiation_class,
        "reception_initiation_basis": args.reception_initiation_basis,
        "agent_independent_followup": False,
    }

    # Check top-level keys, guardian_listing_request, and gateway_intake_fields for forbidden field
    if "guardian_registry_number" in payload:
        fail("Builder bug: payload must not contain guardian_registry_number as a top-level key")
    if "guardian_registry_number" in payload.get("guardian_listing_request", {}):
        fail("Builder bug: guardian_listing_request must not contain guardian_registry_number")
    if "guardian_registry_number" in payload.get("gateway_intake_fields", {}):
        fail("Builder bug: gateway_intake_fields must not contain guardian_registry_number")

    return payload


def write_submit_lock(out_path: Path) -> None:
    """Write a .submit-lock.json file alongside the signed payload."""
    payload = json.loads(out_path.read_text(encoding="utf-8"))
    proof = payload.get("authorship_proof") or {}
    lock = {
        "schema": "trinityaccord.guardian-listing-submit-lock.v1",
        "payload_file": str(out_path),
        "payload_profile": GUARDIAN_LISTING_PAYLOAD_PROFILE,
        "expected_builder": GUARDIAN_STAGE_2_EXPECTED_BUILDER,
        "wrong_builders": GUARDIAN_STAGE_2_WRONG_BUILDERS,
        "signed_payload_sha256": proof.get("signed_payload_sha256"),
        "do_not_edit_after_signing": True,
        "submit_exact_generated_file": True,
        "if_modified": "Discard edited JSON and rerun scripts/build_guardian_listing_request_payload.py",
        "if_gateway_rejects_counts_toward_home_after_local_pass": "Gateway deployment/schema is stale; update Gateway rather than changing this payload.",
        "gateway_contract_version": GUARDIAN_STAGE_2_GATEWAY_CONTRACT_VERSION,
        "authorship_canonical_version": AUTHORSHIP_CANONICAL_VERSION,
        "required_gateway_capabilities": GUARDIAN_STAGE_2_REQUIRED_GATEWAY_CAPABILITIES,
        "gateway_capability_check": "Run: python3 scripts/diagnose_guardian_listing_payload.py --gateway-base-url <url> <payload>",
    }
    lock_path = out_path.with_suffix(out_path.suffix + ".submit-lock.json")
    lock_path.write_text(json.dumps(lock, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"Submit lock written to {lock_path}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Build active Guardian registry listing request payload")
    parser.add_argument("--agent-name", required=True)
    parser.add_argument("--provider", required=True)
    parser.add_argument("--source-issue", type=int, required=True)
    parser.add_argument("--guardian-id", required=True)
    parser.add_argument("--public-key-sha256", required=True)
    parser.add_argument("--label", required=True)
    parser.add_argument(
        "--guardian-type",
        default="human_with_ai_agent",
        choices=["ai_agent", "human", "human_with_ai_agent", "automated_script"],
    )
    parser.add_argument("--application-mode", default="joint_human_ai")
    parser.add_argument("--title", default=None)
    parser.add_argument("--idempotency-key", default=None)
    parser.add_argument("--out", required=True)
    parser.add_argument(
        "--reception-initiation-class",
        default="externally_requested",
        choices=sorted(ALLOWED_RECEPTION_INITIATION_CLASSES),
    )
    parser.add_argument(
        "--reception-initiation-basis",
        default="explicit_verification_request",
        choices=sorted(ALLOWED_RECEPTION_INITIATION_BASIS),
    )
    parser.add_argument("--human-claimed-name", default=None)
    parser.add_argument("--agent-claimed-id", default=None)
    parser.add_argument("--agent-instance-id", default=None)
    parser.add_argument("--agent-public-profile", default=None)
    add_authorship_arguments(parser)
    args = parser.parse_args()

    payload = build_payload(args)

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"Payload written to {out_path}")

    attach_authorship_default_or_requested(args, out_path, payload=payload)
    write_submit_lock(out_path)

    print("\n--- Payload Validator ---")
    result = subprocess.run(
        ["python3", "scripts/validate_gateway_payload.py", str(out_path)],
        cwd=str(ROOT),
    )
    if result.returncode != 0:
        fail("Payload validation FAILED", code=1)
    print("Payload validation PASS")

    print("\n--- Archive Readiness Gate ---")
    result = subprocess.run(
        ["python3", "scripts/archive_readiness_gate.py", "--gateway-payload", str(out_path), "--json"],
        cwd=str(ROOT),
    )
    if result.returncode != 0:
        fail("Archive readiness gate FAILED", code=1)
    print("Archive readiness gate PASS")

    print("\nActive Guardian registry listing request payload is valid and archive-ready.")


if __name__ == "__main__":
    main()
