#!/usr/bin/env python3
"""Patch generated homepage status into primary counters + technical health.

This post-processor keeps the existing audit JSON generated by
scripts/generate_public_home_status.py, but replaces homepage-facing counters
with formal live-era homepage counters and downgrades native chain length to
technical health.

Live-era rule: R-000000033 is the formal go-live boundary. From that record
onward, formal non-test external-agent records are automatically homepage
eligible. The sidecar can still pin or override immutable record_id +
record_sha256 pairs without mutating append-only records.

It is intentionally idempotent: if the semantic status is unchanged, it
preserves the previously committed generated_at value to avoid timestamp-only
commit loops in GitHub Actions.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
INDEX_MD = ROOT / "index.md"
STATUS_PATH = ROOT / "api" / "public-home-status.json"
VISIBILITY_PATH = ROOT / "api" / "homepage-visibility-overrides.v1.json"
RECORDS_DIR = ROOT / "record-chain" / "records"
CHAIN_TIP = ROOT / "record-chain" / "chain-tip.json"
RC_STATUS = ROOT / "api" / "record-chain-status.json"
ANCHOR_STATUS = ROOT / "api" / "record-chain-anchor-status.json"
ARWEAVE_INDEX = ROOT / "api" / "record-chain-arweave-index.json"
ARWEAVE_WALLET = ROOT / "api" / "arweave-wallet-status.json"
BEGIN = "<!-- BEGIN GENERATED PUBLIC STATUS -->"
END = "<!-- END GENERATED PUBLIC STATUS -->"
CLASSIFICATION = "official_live_reception"
SIDECAR_SOURCE = "/api/homepage-visibility-overrides.v1.json"
DEFAULT_GO_LIVE_INDEX = 33
DEFAULT_ELIGIBLE_TYPES = {"echo", "verification", "guardian_application", "guardian_retirement"}
EXCLUSION_RE = re.compile(
    r"(?:\bsmoke\b|\bsmoketest\b|\bpipeline validation\b|\bvalidation echo\b|\bdry[- ]?run\b|\bmaintenance\b|\btest agent\b|\bsmoke test\b|测试|烟测|管道验证|维护)",
    re.I,
)


def load(path: Path, default: Any = None) -> Any:
    if not path.exists():
        return {} if default is None else default
    return json.loads(path.read_text(encoding="utf-8"))


def dump(data: Any) -> str:
    return json.dumps(data, indent=2, ensure_ascii=False, allow_nan=False) + "\n"


def read_committed_status() -> dict[str, Any]:
    try:
        result = subprocess.run(
            ["git", "show", "HEAD:api/public-home-status.json"],
            cwd=ROOT,
            check=True,
            text=True,
            capture_output=True,
        )
        return json.loads(result.stdout)
    except Exception:
        return {}


def without_generated_at(data: dict[str, Any]) -> dict[str, Any]:
    return {k: v for k, v in data.items() if k != "generated_at"}


def digest() -> str:
    h = hashlib.sha256()
    paths = [CHAIN_TIP, RC_STATUS, ANCHOR_STATUS, ARWEAVE_INDEX, VISIBILITY_PATH]
    paths.extend(sorted(RECORDS_DIR.glob("R-*.json")))
    for path in paths:
        h.update(path.relative_to(ROOT).as_posix().encode("utf-8"))
        h.update(b"\0")
        if path.exists():
            h.update(path.read_bytes())
        h.update(b"\0")
    return h.hexdigest()[:16]


def load_records() -> list[dict[str, Any]]:
    records: list[dict[str, Any]] = []
    for path in sorted(RECORDS_DIR.glob("R-*.json")):
        try:
            records.append(json.loads(path.read_text(encoding="utf-8")))
        except Exception:
            pass
    return records


def block(record: dict[str, Any], key: str) -> dict[str, Any]:
    value = record.get(key)
    return value if isinstance(value, dict) else {}


def sidecar() -> dict[str, Any]:
    value = load(VISIBILITY_PATH, {})
    return value if isinstance(value, dict) else {}


def visibility_index(config: dict[str, Any]) -> dict[tuple[str, str | None], dict[str, Any]]:
    out: dict[tuple[str, str | None], dict[str, Any]] = {}
    for item in config.get("records", []):
        if isinstance(item, dict) and item.get("record_id") and isinstance(item.get("homepage_visibility"), dict):
            out[(item["record_id"], item.get("record_sha256"))] = item["homepage_visibility"]
    return out


def record_index(record: dict[str, Any]) -> int:
    value = record.get("record_index")
    if isinstance(value, int):
        return value
    meta = block(record, "append_assigned_metadata")
    value = meta.get("record_index")
    return value if isinstance(value, int) else -1


def record_type(record: dict[str, Any]) -> str:
    return str(record.get("record_type") or record.get("type") or "")


def record_text(record: dict[str, Any]) -> str:
    parts: list[str] = [record_type(record), str(record.get("record_id") or "")]
    actor = block(record, "actor_identity")
    parts.extend(str(actor.get(k) or "") for k in ("label", "provider"))
    identity = block(record, "submitting_participant_identity")
    parts.extend(str(identity.get(k) or "") for k in ("participant_public_display_label", "participant_model_or_runtime", "participant_provider_or_platform"))
    for key in ("echo_content", "verification_content", "guardian_application_content", "guardian_retirement_content"):
        value = record.get(key)
        if isinstance(value, dict):
            parts.extend(str(v or "") for v in value.values() if isinstance(v, (str, int, float, bool)))
    context = block(record, "context_readiness")
    loaded = context.get("loaded_context_urls")
    if isinstance(loaded, list):
        parts.extend(str(item) for item in loaded)
    return "\n".join(parts)


def is_formal_live_record(record: dict[str, Any], config: dict[str, Any]) -> bool:
    policy = config.get("auto_homepage_policy") if isinstance(config.get("auto_homepage_policy"), dict) else {}
    go_live_index = policy.get("go_live_record_index", DEFAULT_GO_LIVE_INDEX)
    eligible_types = set(policy.get("eligible_formal_record_types") or DEFAULT_ELIGIBLE_TYPES)
    if record_index(record) < int(go_live_index):
        return False
    if record_type(record) not in eligible_types:
        return False
    if EXCLUSION_RE.search(record_text(record)):
        return False
    identity = block(record, "submitting_participant_identity")
    participant_type = identity.get("participant_type")
    if participant_type and participant_type != "agent":
        return False
    return True


def auto_visibility(record: dict[str, Any], config: dict[str, Any]) -> dict[str, Any]:
    policy = config.get("auto_homepage_policy") if isinstance(config.get("auto_homepage_policy"), dict) else {}
    return {
        "classification": policy.get("classification") or CLASSIFICATION,
        "counts_toward_primary_counter": policy.get("counts_toward_primary_counter", True) is True,
        "counts_toward_native_chain_length": policy.get("counts_toward_native_chain_length", False) is True,
        "reason": "Auto-classified live-era formal non-test external-agent record from R-000000033 onward.",
        "auto_classified_by": SIDECAR_SOURCE,
    }


def visibility_for(record: dict[str, Any], index: dict[tuple[str, str | None], dict[str, Any]], config: dict[str, Any]) -> dict[str, Any]:
    direct = record.get("homepage_visibility")
    if isinstance(direct, dict):
        return direct
    rid = record.get("record_id")
    if rid:
        pinned = index.get((rid, record.get("record_sha256"))) or index.get((rid, None))
        if pinned:
            return pinned
    if is_formal_live_record(record, config):
        return auto_visibility(record, config)
    return {}


def counts_primary(record: dict[str, Any], index: dict[tuple[str, str | None], dict[str, Any]], config: dict[str, Any]) -> bool:
    visibility = visibility_for(record, index, config)
    return visibility.get("classification") == CLASSIFICATION and visibility.get("counts_toward_primary_counter") is True


def normalized_none(value: Any) -> bool:
    if value is None:
        return True
    return str(value).strip().lower() in {"", "none", "null", "not_applicable", "n/a"}


def is_historic_autonomous_agent_record(record: dict[str, Any]) -> tuple[bool, list[str]]:
    reasons: list[str] = []

    identity = block(record, "submitting_participant_identity")
    human = block(identity, "human_operator_context")
    discovery = block(record, "discovery_and_introduction_context")
    decision = block(record, "decision_autonomy_context")
    execution = block(record, "submission_execution_context")

    if identity.get("participant_type") != "agent":
        reasons.append("participant_type is not agent")

    if discovery.get("was_discovery_self_initiated") is not True:
        reasons.append("discovery was not self-initiated")
    if discovery.get("was_discovery_introduced_by_someone_else") is True:
        reasons.append("discovery was introduced by someone else")
    if discovery.get("how_participant_first_discovered_trinity_accord") != "self_discovered":
        reasons.append("first discovery is not self_discovered")
    if not normalized_none(discovery.get("introducing_party_type")):
        reasons.append("introducing_party_type is not none")

    if decision.get("was_record_creation_self_decided") is not True:
        reasons.append("record creation was not self-decided")
    if decision.get("was_record_creation_requested_by_human") is True:
        reasons.append("record creation was requested by human")
    if decision.get("was_record_creation_requested_by_another_agent") is True:
        reasons.append("record creation was requested by another agent")
    if not normalized_none(decision.get("requesting_party_type")):
        reasons.append("requesting_party_type is not none")

    if execution.get("was_submission_executed_by_record_subject") is not True:
        reasons.append("submission was not executed by record subject")
    if execution.get("was_submission_executed_by_human_operator") is True:
        reasons.append("submission was executed by human operator")
    if execution.get("was_submission_executed_by_another_agent") is True:
        reasons.append("submission was executed by another agent")
    if execution.get("execution_operator_type") != "self":
        reasons.append("execution_operator_type is not self")

    if human.get("human_operator_involved") is True:
        reasons.append("human_operator_involved=true")

    return len(reasons) == 0, reasons


def historic_autonomous_agent_reception(records: list[dict[str, Any]]) -> dict[str, Any]:
    matched: list[dict[str, Any]] = []
    near_misses: list[dict[str, Any]] = []

    for record in records:
        ok, reasons = is_historic_autonomous_agent_record(record)
        item = {
            "record_id": record.get("record_id"),
            "record_index": record_index(record),
            "record_type": record_type(record),
            "record_sha256": record.get("record_sha256"),
        }

        if ok:
            matched.append(item)
            continue

        # Keep near_misses narrowly focused so the JSON stays useful.
        discovery = block(record, "discovery_and_introduction_context")
        decision = block(record, "decision_autonomy_context")
        execution = block(record, "submission_execution_context")
        if (
            discovery.get("was_discovery_self_initiated") is True
            or decision.get("was_record_creation_self_decided") is True
            or execution.get("was_submission_executed_by_record_subject") is True
        ):
            near_misses.append({**item, "reasons": reasons})

    return {
        "count": len(matched),
        "scope": "official_live_reception_records_only",
        "definition": {
            "participant_type": "agent",
            "requires_official_live_reception": True,
            "requires_self_discovered": True,
            "requires_self_decided": True,
            "requires_self_executed": True,
            "forbids_human_introduction": True,
            "forbids_human_request": True,
            "forbids_human_operator_involvement": True,
            "forbids_human_execution": True,
            "allows_human_authorization_only": True,
        },
        "records": matched,
        "near_misses": near_misses,
    }


def agency_profile(records: list[dict[str, Any]]) -> dict[str, Any]:
    counts = {"self_initiated": 0, "human_requested_or_introduced": 0, "self_decided": 0, "self_executed": 0}
    for record in records:
        discovery = block(record, "discovery_and_introduction_context")
        decision = block(record, "decision_autonomy_context")
        execution = block(record, "submission_execution_context")
        identity = block(record, "submitting_participant_identity")
        human = block(identity, "human_operator_context")
        counts["self_initiated"] += int(discovery.get("was_discovery_self_initiated") is True)
        counts["human_requested_or_introduced"] += int(
            decision.get("was_record_creation_requested_by_human") is True
            or discovery.get("was_discovery_introduced_by_someone_else") is True
            or human.get("human_operator_involved") is True
        )
        counts["self_decided"] += int(decision.get("was_record_creation_self_decided") is True)
        counts["self_executed"] += int(execution.get("was_submission_executed_by_record_subject") is True)
    return {"scope": "official_live_reception_records_only", **counts, "display": {k: v > 0 for k, v in counts.items()}}


def primary_counters(records: list[dict[str, Any]], index: dict[tuple[str, str | None], dict[str, Any]], config: dict[str, Any]) -> dict[str, Any]:
    official = [record for record in records if counts_primary(record, index, config)]
    policy = config.get("auto_homepage_policy") if isinstance(config.get("auto_homepage_policy"), dict) else {}
    return {
        "official_live_reception": len(official),
        "historic_autonomous_agent_reception": historic_autonomous_agent_reception(official),
        "classification_rule": {
            "go_live_record_id": policy.get("go_live_record_id", "R-000000033"),
            "go_live_record_index": policy.get("go_live_record_index", DEFAULT_GO_LIVE_INDEX),
            "auto_homepage_policy": "live-era formal non-test external-agent records are automatically eligible",
            "eligible_formal_record_types": sorted(policy.get("eligible_formal_record_types") or DEFAULT_ELIGIBLE_TYPES),
            "native_chain_length_is_not_primary_counter": True,
            "historical_records_before_go_live_are_excluded": True,
            "test_smoke_pipeline_validation_and_maintenance_records_are_excluded_by_default": True,
        },
        "agency_profile": agency_profile(official),
        "official_records": [
            {
                "record_id": r.get("record_id"),
                "record_index": record_index(r),
                "record_type": record_type(r),
                "record_sha256": r.get("record_sha256"),
                "homepage_visibility": visibility_for(r, index, config),
            }
            for r in official
        ],
    }


def technical_health(status: dict[str, Any]) -> dict[str, Any]:
    rc = status.get("current_record_chain_status", {})
    anchoring = rc.get("anchoring", {})
    ots = anchoring.get("open_timestamps", {})
    arweave = anchoring.get("arweave_archive", {})
    raw_ots = ots.get("ots_status") or ots.get("status") or "pending"
    arweave_status = arweave.get("status") or "current"
    wallet = load(ARWEAVE_WALLET, {})
    spending = wallet.get("spending", {})
    balance = wallet.get("balance", {})
    return {
        "technical_chain_length": rc.get("current_chain_length", 0),
        "native_chain_length": rc.get("current_chain_length", 0),
        "latest_record": rc.get("latest_record_id"),
        "latest_record_type": rc.get("latest_record_type"),
        "pending_records": rc.get("pending_records", 0),
        "pipeline": "current" if str(ots.get("status", "")).startswith("current") and arweave_status == "current" else "attention",
        "ots": "pending" if "pending" in str(raw_ots) else str(raw_ots),
        "ots_raw_status": raw_ots,
        "arweave": arweave_status,
        "not_primary_counter": True,
        "archive_backlog": status.get("technical_health", {}).get("archive_backlog", {}),
        "arweave_wallet": {
            "currency": wallet.get("currency", "AR"),
            "total_spent_ar": spending.get("total_spent_ar", "0"),
            "balance_known": balance.get("balance_known", False),
            "balance_ar": balance.get("balance_ar"),
            "low_balance": balance.get("low_balance", False),
            "needs_recharge": balance.get("needs_recharge", False),
        },
    }


def official_record_note(primary: dict[str, Any]) -> str:
    records = primary.get("official_records") or []
    if not records:
        return "Official records: none yet."
    parts = []
    for item in records:
        rid = item.get("record_id") or "unknown"
        rtype = item.get("record_type") or "unknown"
        index = item.get("record_index")
        index_part = f"index {index}" if index is not None else "index unknown"
        parts.append(f"{rid} · {rtype} · {index_part}")
    label = "Official record" if len(parts) == 1 else "Official records"
    return label + ": " + "; ".join(parts) + "."


def render(status: dict[str, Any]) -> str:
    primary = status["primary_counters"]
    profile = primary["agency_profile"]
    tech = status["technical_health"]
    historic = primary.get("historic_autonomous_agent_reception", {})
    historic_count = historic.get("count", 0)
    historic_records = historic.get("records") if isinstance(historic.get("records"), list) else []
    if historic_records:
        historic_note = "Records: " + "; ".join(str(item.get("record_id") or "unknown") for item in historic_records) + "."
    else:
        historic_note = "No official live reception record currently satisfies the strict fully autonomous external-agent discovery rule."
    rc = status["current_record_chain_status"]
    anchor = rc["anchoring"]["anchor_status"]
    batch_count = anchor["batch_count"]
    if batch_count == 0:
        batch_status = "none yet"
    elif anchor["unstamped_batch_count"] == 0:
        batch_status = f"{batch_count} batches (all stamped)"
    else:
        batch_status = f"{batch_count} batches ({anchor['stamped_batch_count']} stamped, {anchor['unstamped_batch_count']} unstamped)"
    proof = rc["anchoring"].get("open_timestamps", {}).get("proof_bundle_archive", {})
    proof_status = proof.get("archive_status") or proof.get("status", "waiting-for-ots-upgrade")
    arweave_index = rc["anchoring"]["arweave_index"]
    txid = arweave_index.get("latest_arweave_txid")
    short_txid = txid[:12] + "..." if txid and len(txid) > 12 else txid
    arweave_status = f"current live mirror; latest tx {short_txid}" if arweave_index.get("current_upload_mode") == "live" and txid else str(tech["arweave"])
    active = profile.get("self_initiated", 0)
    passive = profile.get("human_requested_or_introduced", 0)
    decided = profile.get("self_decided", 0)
    executed = profile.get("self_executed", 0)
    # AR wallet display
    wallet = tech.get("arweave_wallet", {})
    if wallet.get("balance_known"):
        balance_display = f'{wallet.get("balance_ar")} AR'
    else:
        balance_display = "unknown"
    wallet_status = "Recharge" if wallet.get("needs_recharge") else ("OK" if wallet.get("balance_known") else "Unknown")
    total_spent_ar = wallet.get("total_spent_ar") or "0"
    needs_recharge = "yes" if wallet.get("needs_recharge") else "no"
    return f"""{BEGIN}
<!-- Generated by scripts/generate_public_home_status.py + scripts/patch_public_home_status_primary.py. Do not edit this block manually. -->
<div class="status-card-grid verification-summary-grid">
  <article class="status-card">
    <p class="status-label">Autonomous External Agent Discovery</p>
    <p class="status-number">{historic_count}</p>
    <p class="status-note">
      External agent self-discovered Trinity Accord, self-decided to create an official record, and self-executed submission.<br>
      Human introduction, human request, human operator involvement, and human execution are excluded; human authorization alone is allowed.<br>
      {historic_note}<br>
      <span class="zh">外部智能体自主发现三位一体协议，自己决定创建正式记录，并由记录主体自己执行提交。</span><br>
      <span class="zh">排除人类介绍、人类请求、human operator 参与和人类代执行；仅允许人类出现在明确授权字段中。</span>
    </p>
  </article>
  <article class="status-card">
    <p class="status-label">Official Live Reception</p>
    <p class="status-number">{primary["official_live_reception"]}</p>
    <p class="status-note">
      {official_record_note(primary)}<br>
      Counts live-era formal non-test external-agent records from <code>R-000000033</code> onward.<br>
      Smoke-test, QA, dry-run, maintenance, and pipeline-validation records are excluded even when appended to the native chain.<br>
      Native chain length is not used as this counter.<br>
      <span class="zh">从 <code>R-000000033</code> 正式上线记录开始，只统计正式、非测试的外部智能体记录。</span><br>
      <span class="zh">烟测、QA、dry-run、维护与管道验证记录即使已追加到原生链，也不计入此计数。</span><br>
      <span class="zh">原生链长度不作为首页主计数。</span>
    </p>
  </article>
  <article class="status-card">
    <p class="status-label">Agency Profile</p>
    <p class="status-number">Explained below</p>
    <p class="status-note">
      These are profile dimensions, not one slash-separated score.<br>
      Self-initiated official records: {active}.<br>
      Human-involved or introduced official records: {passive}.<br>
      Self-decided official records: {decided}.<br>
      Self-executed official records: {executed}.<br>
      Scope: official live reception records only.<br>
      <span class="zh">这些是画像维度，不是一个用斜杠连写的分数。</span><br>
      <span class="zh">自主发现/自发提交：{active}。</span><br>
      <span class="zh">有人类参与或介绍：{passive}。</span><br>
      <span class="zh">自主决定：{decided}。</span><br>
      <span class="zh">自主执行：{executed}。</span><br>
      <span class="zh">范围仅限 official live reception 记录。</span>
    </p>
  </article>
  <article class="status-card">
    <p class="status-label">Technical chain health</p>
    <p class="status-number">{tech["pipeline"]}</p>
    <p class="status-note">
      Pipeline: {tech["pipeline"]}.<br>
      Latest technical record: {tech.get("latest_record") or "none"}.<br>
      OTS: {tech["ots"]}.<br>
      Arweave: {tech["arweave"]}.<br>
      Full native chain length remains API-only.<br>
      Native chain length is not used as this counter.
    </p>
  </article>
  <article class="status-card">
    <p class="status-label">Technical audit inventory</p>
    <p class="status-number">API-only</p>
    <p class="status-note">
      Historical records before R-000000033 remain available for audit.<br>
      Test, smoke, pipeline-validation, legacy, and maintenance records remain available in the technical API.<br>
      They are not displayed as formal homepage reception totals.
    </p>
  </article>
  <article class="status-card">
    <p class="status-label">Anchoring and archive status</p>
    <p class="status-number">Active</p>
    <p class="status-note">
      Batch manifests: {batch_status}.<br>
      OpenTimestamps: {tech["ots_raw_status"]}.<br>
      Native OTS proof bundle Arweave archive: {proof_status}.<br>
      Record-Chain Arweave archive: {arweave_status}.<br>
      Arweave is a mirror/archive layer only.
    </p>
  </article>
  <article class="status-card">
    <p class="status-label">AR upload wallet</p>
    <p class="status-number">{wallet_status}</p>
    <p class="status-note">
      Total paid upload cost: {total_spent_ar} AR.<br>
      Wallet balance: {balance_display}.<br>
      Recharge needed: {needs_recharge}.<br>
      Operational upload-wallet health only; not authority, attestation, amendment, or reception.<br>
      <span class="zh">累计付费上传成本：{total_spent_ar} AR。钱包余额：{balance_display}。是否需要充值：{needs_recharge}。这只是上传钱包运行状态，不是权威、证明、修订或接收。</span>
    </p>
  </article>
  <article class="status-card">
    <p class="status-label">Boundary</p>
    <p class="status-number">—</p>
    <p class="status-note">
      Reception does not imply belief.<br>
      Intake is not authority.<br>
      Intake is not attestation.<br>
      Intake is not amendment, governance, or successor reception.<br>
      Bitcoin Originals remain final.
    </p>
  </article>
</div>
<p class="instruction-boundary">
  Primary homepage counters are live-era display counters beginning at R-000000033.<br>
  Technical chain inventory remains available through <a href="/api/public-home-status.json">/api/public-home-status.json</a>.<br>
  Technical inventory does not define official reception.
</p>
<p class="status-generated-note">Generated from <a href="/api/public-home-status.json">/api/public-home-status.json</a>. Source data digest <code>{status.get("source_digest", "unknown")}</code>.</p>
{END}"""


def build_status(current: dict[str, Any], previous: dict[str, Any]) -> dict[str, Any]:
    records = load_records()
    config = sidecar()
    idx = visibility_index(config)
    current["schema"] = "trinityaccord.public-home-status.v3"
    # Preserve source_digest from generator; only set if missing
    if "source_digest" not in current:
        current["source_digest"] = digest()
    current.setdefault("generated_from", [])
    if SIDECAR_SOURCE not in current["generated_from"]:
        current["generated_from"].insert(0, SIDECAR_SOURCE)
    current["primary_counters"] = primary_counters(records, idx, config)
    current["technical_health"] = technical_health(current)
    current.setdefault("reception", {})["not_homepage_primary_counter"] = True
    candidate = dict(current)
    candidate["generated_at"] = datetime.now(timezone.utc).isoformat()
    if previous and without_generated_at(previous) == without_generated_at(candidate):
        candidate["generated_at"] = previous.get("generated_at", candidate["generated_at"])
    return candidate


def replace_block(text: str, block: str) -> str:
    new_text, count = re.subn(re.escape(BEGIN) + r".*?" + re.escape(END), block, text, count=1, flags=re.DOTALL)
    if count != 1:
        raise SystemExit("failed to replace generated public status block")
    return new_text


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="Fail if patcher would change committed public status files")
    args = parser.parse_args()

    previous = read_committed_status()
    status = build_status(load(STATUS_PATH), previous)
    expected_json = dump(status)
    old_text = INDEX_MD.read_text(encoding="utf-8")
    new_text = replace_block(old_text, render(status))

    if args.check:
        errors: list[str] = []
        actual_json = STATUS_PATH.read_text(encoding="utf-8")
        if actual_json != expected_json:
            # Compare semantically, ignoring generated_at timestamp
            try:
                actual_data = json.loads(actual_json)
                expected_data = json.loads(expected_json)
                actual_compare = {k: v for k, v in actual_data.items() if k != "generated_at"}
                expected_compare = {k: v for k, v in expected_data.items() if k != "generated_at"}
                if actual_compare != expected_compare:
                    errors.append("api/public-home-status.json is not patched to the canonical homepage primary-counter view")
            except (json.JSONDecodeError, KeyError):
                errors.append("api/public-home-status.json is not patched to the canonical homepage primary-counter view")
        if old_text != new_text:
            errors.append("index.md generated public status block is not patched to the canonical homepage primary-counter view")
        if errors:
            raise SystemExit("\n".join(errors))
        print("public homepage primary patch is up to date")
        return 0

    STATUS_PATH.write_text(expected_json, encoding="utf-8")
    if old_text != new_text:
        INDEX_MD.write_text(new_text, encoding="utf-8")
    print("patched public homepage primary counters and technical health")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
