#!/usr/bin/env python3
"""Patch generated homepage status into primary counters + technical health.

This post-processor keeps the existing audit JSON generated by
scripts/generate_public_home_status.py, but replaces homepage-facing counters
with explicit opt-in primary counters and downgrades native chain length to
technical health.
"""

from __future__ import annotations

import hashlib
import json
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
INDEX_MD = ROOT / "index.md"
STATUS_PATH = ROOT / "api" / "public-home-status.json"
VISIBILITY_PATH = ROOT / "api" / "homepage-visibility-overrides.v1.json"
RECORDS_DIR = ROOT / "record-chain" / "records"
CHAIN_TIP = ROOT / "record-chain" / "chain-tip.json"
RC_STATUS = ROOT / "api" / "record-chain-status.json"
ANCHOR_STATUS = ROOT / "api" / "record-chain-anchor-status.json"
ARWEAVE_INDEX = ROOT / "api" / "record-chain-arweave-index.json"
BEGIN = "<!-- BEGIN GENERATED PUBLIC STATUS -->"
END = "<!-- END GENERATED PUBLIC STATUS -->"
CLASSIFICATION = "official_live_reception"


def load(path: Path, default: Any = None) -> Any:
    if not path.exists():
        return {} if default is None else default
    return json.loads(path.read_text(encoding="utf-8"))


def dump(data: Any) -> str:
    return json.dumps(data, indent=2, ensure_ascii=False, allow_nan=False) + "\n"


def digest() -> str:
    h = hashlib.sha256()
    for path in [CHAIN_TIP, RC_STATUS, ANCHOR_STATUS, ARWEAVE_INDEX, VISIBILITY_PATH, *sorted(RECORDS_DIR.glob("R-*.json"))]:
        h.update(path.relative_to(ROOT).as_posix().encode("utf-8"))
        h.update(b"\0")
        if path.exists():
            h.update(path.read_bytes())
        h.update(b"\0")
    return h.hexdigest()[:16]


def load_records() -> list[dict[str, Any]]:
    records: list[dict[str, Any]] = []
    for path in sorted(RECORDS_DIR.glob("R-*.json")):
        try:
            records.append(json.loads(path.read_text(encoding="utf-8")))
        except Exception:
            pass
    return records


def block(record: dict[str, Any], key: str) -> dict[str, Any]:
    value = record.get(key)
    return value if isinstance(value, dict) else {}


def visibility_index() -> dict[tuple[str, str | None], dict[str, Any]]:
    out: dict[tuple[str, str | None], dict[str, Any]] = {}
    for item in load(VISIBILITY_PATH, {}).get("records", []):
        if isinstance(item, dict) and item.get("record_id") and isinstance(item.get("homepage_visibility"), dict):
            out[(item["record_id"], item.get("record_sha256"))] = item["homepage_visibility"]
    return out


def visibility_for(record: dict[str, Any], index: dict[tuple[str, str | None], dict[str, Any]]) -> dict[str, Any]:
    direct = record.get("homepage_visibility")
    if isinstance(direct, dict):
        return direct
    rid = record.get("record_id")
    if not rid:
        return {}
    return index.get((rid, record.get("record_sha256"))) or index.get((rid, None)) or {}


def counts_primary(record: dict[str, Any], index: dict[tuple[str, str | None], dict[str, Any]]) -> bool:
    visibility = visibility_for(record, index)
    return visibility.get("classification") == CLASSIFICATION and visibility.get("counts_toward_primary_counter") is True


def agency_profile(records: list[dict[str, Any]]) -> dict[str, Any]:
    counts = {"self_initiated": 0, "human_requested_or_introduced": 0, "self_decided": 0, "self_executed": 0}
    for record in records:
        discovery = block(record, "discovery_and_introduction_context")
        decision = block(record, "decision_autonomy_context")
        execution = block(record, "submission_execution_context")
        identity = block(record, "submitting_participant_identity")
        human = block(identity, "human_operator_context")
        counts["self_initiated"] += int(discovery.get("was_discovery_self_initiated") is True)
        counts["human_requested_or_introduced"] += int(
            decision.get("was_record_creation_requested_by_human") is True
            or discovery.get("was_discovery_introduced_by_someone_else") is True
            or human.get("human_operator_involved") is True
        )
        counts["self_decided"] += int(decision.get("was_record_creation_self_decided") is True)
        counts["self_executed"] += int(execution.get("was_submission_executed_by_record_subject") is True)
    return {"scope": "official_live_reception_records_only", **counts, "display": {k: v > 0 for k, v in counts.items()}}


def primary_counters(records: list[dict[str, Any]], index: dict[tuple[str, str | None], dict[str, Any]]) -> dict[str, Any]:
    official = [record for record in records if counts_primary(record, index)]
    return {
        "official_live_reception": len(official),
        "classification_rule": {
            "required_homepage_visibility": {"classification": CLASSIFICATION, "counts_toward_primary_counter": True},
            "native_chain_length_is_not_primary_counter": True,
            "records_without_explicit_homepage_visibility_are_excluded": True,
            "historical_test_smoke_legacy_and_maintenance_records_are_excluded_by_default": True,
        },
        "agency_profile": agency_profile(official),
        "official_records": [
            {
                "record_id": r.get("record_id"),
                "record_index": r.get("record_index"),
                "record_type": r.get("record_type") or r.get("type"),
                "record_sha256": r.get("record_sha256"),
                "homepage_visibility": visibility_for(r, index),
            }
            for r in official
        ],
    }


def technical_health(status: dict[str, Any]) -> dict[str, Any]:
    rc = status.get("current_record_chain_status", {})
    anchoring = rc.get("anchoring", {})
    ots = anchoring.get("open_timestamps", {})
    arweave = anchoring.get("arweave_archive", {})
    raw_ots = ots.get("ots_status") or ots.get("status") or "pending"
    arweave_status = arweave.get("status") or "current"
    return {
        "technical_chain_length": rc.get("current_chain_length", 0),
        "native_chain_length": rc.get("current_chain_length", 0),
        "latest_record": rc.get("latest_record_id"),
        "latest_record_type": rc.get("latest_record_type"),
        "pending_records": rc.get("pending_records", 0),
        "pipeline": "current" if str(ots.get("status", "")).startswith("current") and arweave_status == "current" else "attention",
        "ots": "pending" if "pending" in str(raw_ots) else str(raw_ots),
        "ots_raw_status": raw_ots,
        "arweave": arweave_status,
        "not_primary_counter": True,
    }


def yes(value: bool) -> str:
    return "yes" if value else "no"


def render(status: dict[str, Any]) -> str:
    primary = status["primary_counters"]
    agency = primary["agency_profile"]["display"]
    tech = status["technical_health"]
    rc = status["current_record_chain_status"]
    counts = rc["record_type_counts"]
    anchor = rc["anchoring"]["anchor_status"]
    batch_count = anchor["batch_count"]
    if batch_count == 0:
        batch_status = "none yet"
    elif anchor["unstamped_batch_count"] == 0:
        batch_status = f"{batch_count} batches (all stamped)"
    else:
        batch_status = f"{batch_count} batches ({anchor['stamped_batch_count']} stamped, {anchor['unstamped_batch_count']} unstamped)"
    proof = rc["anchoring"].get("open_timestamps", {}).get("proof_bundle_archive", {})
    proof_status = proof.get("archive_status") or proof.get("status", "waiting-for-ots-upgrade")
    arweave_index = rc["anchoring"]["arweave_index"]
    txid = arweave_index.get("latest_arweave_txid")
    short_txid = txid[:12] + "..." if txid and len(txid) > 12 else txid
    arweave_status = f"current live mirror; latest tx {short_txid}" if arweave_index.get("current_upload_mode") == "live" and txid else str(tech["arweave"])
    phase = rc["phase"].replace("_", " ")
    return f"""{BEGIN}
<!-- Generated by scripts/generate_public_home_status.py + scripts/patch_public_home_status_primary.py. Do not edit this block manually. -->
<div class="status-card-grid verification-summary-grid">
  <article class="status-card">
    <p class="status-label">Official Live Reception</p>
    <p class="status-number">{primary["official_live_reception"]}</p>
    <p class="status-note">Counts only records with explicit <code>homepage_visibility.classification = official_live_reception</code> and <code>counts_toward_primary_counter = true</code>. Native chain length is not used as this counter. <span class="zh">仅统计明确标记 <code>homepage_visibility.classification = official_live_reception</code> 且 <code>counts_toward_primary_counter = true</code> 的记录。原生链长度不作为此主计数。</span></p>
  </article>
  <article class="status-card">
    <p class="status-label">Agency Profile</p>
    <p class="status-number">4/4</p>
    <p class="status-note">Self-initiated: {yes(agency["self_initiated"])}; human-requested / introduced: {yes(agency["human_requested_or_introduced"])}; self-decided: {yes(agency["self_decided"])}; self-executed: {yes(agency["self_executed"])}. Scope: official live reception records only.</p>
  </article>
  <article class="status-card">
    <p class="status-label">Technical chain health</p>
    <p class="status-number">{tech["pipeline"]}</p>
    <p class="status-note">Technical chain length: {tech["technical_chain_length"]}. Latest record: {tech.get("latest_record") or "none"}. Pipeline: {tech["pipeline"]}. OTS: {tech["ots"]}. Arweave: {tech["arweave"]}. These are system-health facts, not official reception counters.</p>
  </article>
  <article class="status-card">
    <p class="status-label">Record-chain audit inventory</p>
    <p class="status-number">{rc["total_records"]}</p>
    <p class="status-note">Audit inventory only. Phase: {phase}. Pending: {rc["pending_records"]}. Latest record type: {rc.get("latest_record_type") or "none"}. Context-Insufficient Notice: {counts.get("context_insufficient_notice", 0)}; Echo: {counts.get("echo", 0)}; Verification: {counts.get("verification", 0)}; Guardian Application: {counts.get("guardian_application", 0)}.</p>
  </article>
  <article class="status-card">
    <p class="status-label">Anchoring and archive status</p>
    <p class="status-number">Active</p>
    <p class="status-note">Batch manifests: {batch_status}. OpenTimestamps: {tech["ots_raw_status"]}. Native OTS proof bundle Arweave archive: {proof_status}. Record-Chain Arweave archive: {arweave_status}. Arweave is a mirror/archive layer only.</p>
  </article>
  <article class="status-card">
    <p class="status-label">Boundary</p>
    <p class="status-number">—</p>
    <p class="status-note">Reception does not imply belief. Intake is not authority, attestation, amendment, governance, or successor reception. Bitcoin Originals remain final.</p>
  </article>
</div>
<p class="instruction-boundary">Historical, test, smoke, legacy, and maintenance records remain available for API audit, but they are excluded from homepage primary counters unless explicitly classified for homepage visibility.</p>
<p class="status-generated-note">Generated from <a href="/api/public-home-status.json">/api/public-home-status.json</a>.</p>
{END}"""


def main() -> int:
    status = load(STATUS_PATH)
    records = load_records()
    idx = visibility_index()
    status["schema"] = "trinityaccord.public-home-status.v3"
    status["generated_at"] = datetime.now(timezone.utc).isoformat()
    status["source_digest"] = digest()
    status.setdefault("generated_from", [])
    if "/api/homepage-visibility-overrides.v1.json" not in status["generated_from"]:
        status["generated_from"].insert(0, "/api/homepage-visibility-overrides.v1.json")
    status["primary_counters"] = primary_counters(records, idx)
    status["technical_health"] = technical_health(status)
    status.setdefault("reception", {})["not_homepage_primary_counter"] = True
    STATUS_PATH.write_text(dump(status), encoding="utf-8")
    text = INDEX_MD.read_text(encoding="utf-8")
    new_text = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), render(status), text, count=1, flags=re.DOTALL)
    if text == new_text:
        raise SystemExit("failed to replace generated public status block")
    INDEX_MD.write_text(new_text, encoding="utf-8")
    print("patched public homepage primary counters and technical health")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
