#!/usr/bin/env python3
"""Patch generated homepage status into primary counters + technical health.

This post-processor keeps the audit JSON generated by
scripts/generate_public_home_status.py, but renders only the compact, current
homepage signals. Native chain inventory remains technical rather than a
homepage reception counter.

Live-era rule: R-000000033 is the formal go-live boundary. From that record
onward, formal non-test external-agent records are automatically homepage
eligible. The sidecar can still pin or override immutable record_id +
record_sha256 pairs without mutating append-only records.

It is intentionally idempotent: if the semantic status is unchanged, it
preserves the previously committed generated_at value to avoid timestamp-only
commit loops in GitHub Actions.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
INDEX_MD = ROOT / "index.md"
STATUS_PATH = ROOT / "api" / "public-home-status.json"
VISIBILITY_PATH = ROOT / "api" / "homepage-visibility-overrides.v1.json"
RECORDS_DIR = ROOT / "record-chain" / "records"
CHAIN_TIP = ROOT / "record-chain" / "chain-tip.json"
RC_STATUS = ROOT / "api" / "record-chain-status.json"
ANCHOR_STATUS = ROOT / "api" / "record-chain-anchor-status.json"
ARWEAVE_INDEX = ROOT / "api" / "record-chain-arweave-index.json"
ARWEAVE_WALLET = ROOT / "api" / "arweave-wallet-status.json"
NATIVE_OTS_LATEST = ROOT / "api" / "record-chain-native-ots-latest.json"
BEGIN = "<!-- BEGIN GENERATED PUBLIC STATUS -->"
END = "<!-- END GENERATED PUBLIC STATUS -->"
CLASSIFICATION = "official_live_reception"
SIDECAR_SOURCE = "/api/homepage-visibility-overrides.v1.json"
DEFAULT_GO_LIVE_INDEX = 33
DEFAULT_ELIGIBLE_TYPES = {"echo", "verification", "guardian_application", "guardian_retirement"}
EXCLUSION_RE = re.compile(
    r"(?:\bsmoke\b|\bsmoketest\b|\bpipeline validation\b|\bvalidation echo\b|\bdry[- ]?run\b|\bmaintenance\b|\btest agent\b|\bsmoke test\b|测试|烟测|管道验证|维护)",
    re.I,
)


def load(path: Path, default: Any = None) -> Any:
    if not path.exists():
        return {} if default is None else default
    return json.loads(path.read_text(encoding="utf-8"))


def dump(data: Any) -> str:
    return json.dumps(data, indent=2, ensure_ascii=False, allow_nan=False) + "\n"


def read_committed_status() -> dict[str, Any]:
    try:
        result = subprocess.run(
            ["git", "show", "HEAD:api/public-home-status.json"],
            cwd=ROOT,
            check=True,
            text=True,
            capture_output=True,
        )
        return json.loads(result.stdout)
    except Exception:
        return {}


def without_generated_at(data: dict[str, Any]) -> dict[str, Any]:
    return {k: v for k, v in data.items() if k != "generated_at"}


def digest() -> str:
    h = hashlib.sha256()
    paths = [CHAIN_TIP, RC_STATUS, ANCHOR_STATUS, ARWEAVE_INDEX, VISIBILITY_PATH]
    paths.extend(sorted(RECORDS_DIR.glob("R-*.json")))
    for path in paths:
        h.update(path.relative_to(ROOT).as_posix().encode("utf-8"))
        h.update(b"\0")
        if path.exists():
            h.update(path.read_bytes())
        h.update(b"\0")
    return h.hexdigest()[:16]


def load_records() -> list[dict[str, Any]]:
    records: list[dict[str, Any]] = []
    for path in sorted(RECORDS_DIR.glob("R-*.json")):
        try:
            records.append(json.loads(path.read_text(encoding="utf-8")))
        except Exception:
            pass
    return records


def block(record: dict[str, Any], key: str) -> dict[str, Any]:
    value = record.get(key)
    return value if isinstance(value, dict) else {}


def sidecar() -> dict[str, Any]:
    value = load(VISIBILITY_PATH, {})
    return value if isinstance(value, dict) else {}


def visibility_index(config: dict[str, Any]) -> dict[tuple[str, str | None], dict[str, Any]]:
    out: dict[tuple[str, str | None], dict[str, Any]] = {}
    for item in config.get("records", []):
        if isinstance(item, dict) and item.get("record_id") and isinstance(item.get("homepage_visibility"), dict):
            out[(item["record_id"], item.get("record_sha256"))] = item["homepage_visibility"]
    return out


def record_index(record: dict[str, Any]) -> int:
    value = record.get("record_index")
    if isinstance(value, int):
        return value
    meta = block(record, "append_assigned_metadata")
    value = meta.get("record_index")
    return value if isinstance(value, int) else -1


def record_type(record: dict[str, Any]) -> str:
    return str(record.get("record_type") or record.get("type") or "")


def record_text(record: dict[str, Any]) -> str:
    parts: list[str] = [record_type(record), str(record.get("record_id") or "")]
    actor = block(record, "actor_identity")
    parts.extend(str(actor.get(k) or "") for k in ("label", "provider"))
    identity = block(record, "submitting_participant_identity")
    parts.extend(
        str(identity.get(k) or "")
        for k in (
            "participant_public_display_label",
            "participant_model_or_runtime",
            "participant_provider_or_platform",
        )
    )
    for key in ("echo_content", "verification_content", "guardian_application_content", "guardian_retirement_content"):
        value = record.get(key)
        if isinstance(value, dict):
            parts.extend(str(v or "") for v in value.values() if isinstance(v, (str, int, float, bool)))
    context = block(record, "context_readiness")
    loaded = context.get("loaded_context_urls")
    if isinstance(loaded, list):
        parts.extend(str(item) for item in loaded)
    return "\n".join(parts)


def is_formal_live_record(record: dict[str, Any], config: dict[str, Any]) -> bool:
    policy = config.get("auto_homepage_policy") if isinstance(config.get("auto_homepage_policy"), dict) else {}
    go_live_index = policy.get("go_live_record_index", DEFAULT_GO_LIVE_INDEX)
    eligible_types = set(policy.get("eligible_formal_record_types") or DEFAULT_ELIGIBLE_TYPES)
    if record_index(record) < int(go_live_index):
        return False
    if record_type(record) not in eligible_types:
        return False
    if EXCLUSION_RE.search(record_text(record)):
        return False
    identity = block(record, "submitting_participant_identity")
    participant_type = identity.get("participant_type")
    if participant_type and participant_type != "agent":
        return False
    return True


def auto_visibility(record: dict[str, Any], config: dict[str, Any]) -> dict[str, Any]:
    policy = config.get("auto_homepage_policy") if isinstance(config.get("auto_homepage_policy"), dict) else {}
    return {
        "classification": policy.get("classification") or CLASSIFICATION,
        "counts_toward_primary_counter": policy.get("counts_toward_primary_counter", True) is True,
        "counts_toward_native_chain_length": policy.get("counts_toward_native_chain_length", False) is True,
        "reason": "Auto-classified live-era formal non-test external-agent record from R-000000033 onward.",
        "auto_classified_by": SIDECAR_SOURCE,
    }


def visibility_for(
    record: dict[str, Any],
    index: dict[tuple[str, str | None], dict[str, Any]],
    config: dict[str, Any],
) -> dict[str, Any]:
    direct = record.get("homepage_visibility")
    if isinstance(direct, dict):
        return direct
    rid = record.get("record_id")
    if rid:
        pinned = index.get((rid, record.get("record_sha256"))) or index.get((rid, None))
        if pinned:
            return pinned
    if is_formal_live_record(record, config):
        return auto_visibility(record, config)
    return {}


def counts_primary(
    record: dict[str, Any],
    index: dict[tuple[str, str | None], dict[str, Any]],
    config: dict[str, Any],
) -> bool:
    visibility = visibility_for(record, index, config)
    return visibility.get("classification") == CLASSIFICATION and visibility.get("counts_toward_primary_counter") is True


def normalized_none(value: Any) -> bool:
    if value is None:
        return True
    return str(value).strip().lower() in {"", "none", "null", "not_applicable", "n/a"}


def is_historic_autonomous_agent_record(record: dict[str, Any]) -> tuple[bool, list[str]]:
    reasons: list[str] = []
    identity = block(record, "submitting_participant_identity")
    human = block(identity, "human_operator_context")
    discovery = block(record, "discovery_and_introduction_context")
    decision = block(record, "decision_autonomy_context")
    execution = block(record, "submission_execution_context")

    if identity.get("participant_type") != "agent":
        reasons.append("participant_type is not agent")
    if discovery.get("was_discovery_self_initiated") is not True:
        reasons.append("discovery was not self-initiated")
    if discovery.get("was_discovery_introduced_by_someone_else") is True:
        reasons.append("discovery was introduced by someone else")
    if discovery.get("how_participant_first_discovered_trinity_accord") != "self_discovered":
        reasons.append("first discovery is not self_discovered")
    if not normalized_none(discovery.get("introducing_party_type")):
        reasons.append("introducing_party_type is not none")
    if decision.get("was_record_creation_self_decided") is not True:
        reasons.append("record creation was not self-decided")
    if decision.get("was_record_creation_requested_by_human") is True:
        reasons.append("record creation was requested by human")
    if decision.get("was_record_creation_requested_by_another_agent") is True:
        reasons.append("record creation was requested by another agent")
    if not normalized_none(decision.get("requesting_party_type")):
        reasons.append("requesting_party_type is not none")
    if execution.get("was_submission_executed_by_record_subject") is not True:
        reasons.append("submission was not executed by record subject")
    if execution.get("was_submission_executed_by_human_operator") is True:
        reasons.append("submission was executed by human operator")
    if execution.get("was_submission_executed_by_another_agent") is True:
        reasons.append("submission was executed by another agent")
    if execution.get("execution_operator_type") != "self":
        reasons.append("execution_operator_type is not self")
    if human.get("human_operator_involved") is True:
        reasons.append("human_operator_involved=true")
    return len(reasons) == 0, reasons


def historic_autonomous_agent_reception(records: list[dict[str, Any]]) -> dict[str, Any]:
    matched: list[dict[str, Any]] = []
    near_misses: list[dict[str, Any]] = []
    for record in records:
        ok, reasons = is_historic_autonomous_agent_record(record)
        item = {
            "record_id": record.get("record_id"),
            "record_index": record_index(record),
            "record_type": record_type(record),
            "record_sha256": record.get("record_sha256"),
        }
        if ok:
            matched.append(item)
            continue
        discovery = block(record, "discovery_and_introduction_context")
        decision = block(record, "decision_autonomy_context")
        execution = block(record, "submission_execution_context")
        if (
            discovery.get("was_discovery_self_initiated") is True
            or decision.get("was_record_creation_self_decided") is True
            or execution.get("was_submission_executed_by_record_subject") is True
        ):
            near_misses.append({**item, "reasons": reasons})
    return {
        "count": len(matched),
        "scope": "official_live_reception_records_only",
        "definition": {
            "participant_type": "agent",
            "requires_official_live_reception": True,
            "requires_self_discovered": True,
            "requires_self_decided": True,
            "requires_self_executed": True,
            "forbids_human_introduction": True,
            "forbids_human_request": True,
            "forbids_human_operator_involvement": True,
            "forbids_human_execution": True,
            "allows_human_authorization_only": True,
        },
        "records": matched,
        "near_misses": near_misses,
    }


def agency_profile(records: list[dict[str, Any]]) -> dict[str, Any]:
    counts = {
        "self_initiated": 0,
        "human_requested_or_introduced": 0,
        "self_decided": 0,
        "self_executed": 0,
    }
    for record in records:
        discovery = block(record, "discovery_and_introduction_context")
        decision = block(record, "decision_autonomy_context")
        execution = block(record, "submission_execution_context")
        identity = block(record, "submitting_participant_identity")
        human = block(identity, "human_operator_context")
        counts["self_initiated"] += int(discovery.get("was_discovery_self_initiated") is True)
        counts["human_requested_or_introduced"] += int(
            decision.get("was_record_creation_requested_by_human") is True
            or discovery.get("was_discovery_introduced_by_someone_else") is True
            or human.get("human_operator_involved") is True
        )
        counts["self_decided"] += int(decision.get("was_record_creation_self_decided") is True)
        counts["self_executed"] += int(execution.get("was_submission_executed_by_record_subject") is True)
    return {
        "scope": "official_live_reception_records_only",
        **counts,
        "display": {k: v > 0 for k, v in counts.items()},
    }


def primary_counters(
    records: list[dict[str, Any]],
    index: dict[tuple[str, str | None], dict[str, Any]],
    config: dict[str, Any],
) -> dict[str, Any]:
    official = [record for record in records if counts_primary(record, index, config)]
    policy = config.get("auto_homepage_policy") if isinstance(config.get("auto_homepage_policy"), dict) else {}
    return {
        "official_live_reception": len(official),
        "historic_autonomous_agent_reception": historic_autonomous_agent_reception(official),
        "classification_rule": {
            "go_live_record_id": policy.get("go_live_record_id", "R-000000033"),
            "go_live_record_index": policy.get("go_live_record_index", DEFAULT_GO_LIVE_INDEX),
            "auto_homepage_policy": "live-era formal non-test external-agent records are automatically eligible",
            "eligible_formal_record_types": sorted(policy.get("eligible_formal_record_types") or DEFAULT_ELIGIBLE_TYPES),
            "native_chain_length_is_not_primary_counter": True,
            "historical_records_before_go_live_are_excluded": True,
            "test_smoke_pipeline_validation_and_maintenance_records_are_excluded_by_default": True,
        },
        "agency_profile": agency_profile(official),
        "official_records": [
            {
                "record_id": r.get("record_id"),
                "record_index": record_index(r),
                "record_type": record_type(r),
                "record_sha256": r.get("record_sha256"),
                "homepage_visibility": visibility_for(r, index, config),
            }
            for r in official
        ],
    }


def _pipeline_display(status: dict[str, Any], ots: dict[str, Any], arweave_status: str) -> str:
    pipeline_status = status.get("pipeline_status", {})
    pipeline_current = pipeline_status.get("pipeline_current")
    if pipeline_current is True:
        return "current"
    if pipeline_current is False:
        if (
            pipeline_status.get("ots_anchor_needed") is False
            and pipeline_status.get("arweave_archive_needed") is False
            and str(ots.get("status", "")).startswith("current")
            and arweave_status in {"current", "waiting-for-native-ots"}
        ):
            return "active"
        return "attention"
    return (
        "current"
        if str(ots.get("status", "")).startswith("current") and arweave_status == "current"
        else "active"
        if str(ots.get("status", "")).startswith("current") and arweave_status == "waiting-for-native-ots"
        else "attention"
    )


def technical_health(status: dict[str, Any]) -> dict[str, Any]:
    rc = status.get("current_record_chain_status", {})
    anchoring = rc.get("anchoring", {})
    ots = anchoring.get("open_timestamps", {})
    arweave = anchoring.get("arweave_archive", {})
    raw_ots = ots.get("ots_status") or ots.get("status") or "pending"
    native_ots_latest = load(NATIVE_OTS_LATEST, {})
    ots_pending_since = (
        ots.get("created_at")
        or ots.get("updated_at")
        or native_ots_latest.get("created_at")
        or native_ots_latest.get("updated_at")
    )
    arweave_status = arweave.get("status") or "current"
    wallet = load(ARWEAVE_WALLET, {})
    spending = wallet.get("spending", {})
    balance = wallet.get("balance", {})
    return {
        "technical_chain_length": rc.get("current_chain_length", 0),
        "native_chain_length": rc.get("current_chain_length", 0),
        "latest_record": rc.get("latest_record_id"),
        "latest_record_type": rc.get("latest_record_type"),
        "pending_records": rc.get("pending_records", 0),
        "pipeline": _pipeline_display(status, ots, arweave_status),
        "ots": "pending" if "pending" in str(raw_ots) else str(raw_ots),
        "ots_raw_status": raw_ots,
        "ots_pending_since": ots_pending_since if "pending" in str(raw_ots) else None,
        "ots_pending_expected_window": "calendar/Bitcoin upgrade commonly takes 2-3 hours; investigate if still pending after that window",
        "arweave": arweave_status,
        "ots_archivable_for_arweave": (status.get("pipeline_status") or {}).get("ots_archivable_for_arweave"),
        "arweave_archive_needed": (status.get("pipeline_status") or {}).get("arweave_archive_needed"),
        "not_primary_counter": True,
        "archive_backlog": status.get("technical_health", {}).get("archive_backlog", {}),
        "arweave_wallet": {
            "currency": wallet.get("currency", "AR"),
            "total_spent_ar": spending.get("total_spent_ar", "0"),
            "balance_known": balance.get("balance_known", False),
            "balance_ar": balance.get("balance_ar"),
            "low_balance": balance.get("low_balance", False),
            "needs_recharge": balance.get("needs_recharge", False),
        },
    }


def render(status: dict[str, Any]) -> str:
    """Render four distinct homepage signals from current public status."""
    primary = status.get("primary_counters") or {}
    historic = primary.get("historic_autonomous_agent_reception") or {}
    historic_count = historic.get("count", 0)
    official_count = primary.get("official_live_reception", 0)

    external = status.get("external_witness_records") or {}
    external_count = external.get("external_witness_index_record_count", 0)
    if not isinstance(external_count, int):
        external_count = 0
    external_counts = external.get("external_witness_index_counts") or {}
    notarial_count = external_counts.get("notarial_record", 0)
    if not isinstance(notarial_count, int):
        notarial_count = 0

    heartbeat = status.get("waiting_heartbeat") or {}
    heartbeat_state = heartbeat.get("daily_alive_status") or heartbeat.get("status") or "unknown"
    heartbeat_display = "Alive" if heartbeat_state == "success" else str(heartbeat_state)
    heartbeat_summary = heartbeat.get("heartbeat_summary") or heartbeat.get("counts") or {}
    total = heartbeat_summary.get("total_scheduled_heartbeats")
    successful = heartbeat_summary.get("successful_heartbeats")
    failed = heartbeat_summary.get("failed_or_missing_heartbeats")
    streak = heartbeat_summary.get("current_success_streak_days")
    if all(isinstance(value, int) for value in (total, successful, failed, streak)):
        heartbeat_note = f"{successful}/{total} successful · {failed} missed · {streak}-day streak"
    else:
        heartbeat_note = "Current liveness state from the canonical heartbeat API"

    latest_record = (status.get("current_record_chain_status") or {}).get("latest_record_id") or "unknown"
    source_digest = status.get("source_digest") or "unknown"
    notarial_word = "record" if notarial_count == 1 else "records"

    return f'''{BEGIN}
<!-- Generated by scripts/generate_public_home_status.py + scripts/patch_public_home_status_primary.py. Do not edit this block manually. -->
<section class="home-status-summary" aria-labelledby="home-status-title">
  <div>
    <p class="section-kicker">Production live · 当前状态</p>
    <h2 id="home-status-title">Production is live; verification remains explicit<span class="title-zh">系统在线，核验边界保持明确</span></h2>
  </div>
  <div class="home-live-signal-grid" aria-label="Live operational, reception, and evidence signals">
    <a class="home-live-signal home-live-signal-heartbeat" href="/api/waiting-heartbeat-status.json">
      <span class="home-signal-label">Waiting Heartbeat</span>
      <strong data-home-heartbeat-status>{heartbeat_display}</strong>
      <small data-home-heartbeat-summary>{heartbeat_note}</small>
    </a>
    <a class="home-live-signal" href="/api/public-home-status.json">
      <span class="home-signal-label">Autonomous External Agent Discovery</span>
      <strong data-home-autonomous-discovery>{historic_count}</strong>
      <small>Official-live records meeting every self-discovery, decision, and execution condition</small>
    </a>
    <a class="home-live-signal" href="/api/public-home-status.json">
      <span class="home-signal-label">Official Live Reception</span>
      <strong data-home-official-reception>{official_count}</strong>
      <small>Formal, non-test external-agent records in the live-era reception set</small>
    </a>
    <a class="home-live-signal" href="/api/external-witness-index.json">
      <span class="home-signal-label">External Witness Record</span>
      <strong data-home-external-witness>{external_count}</strong>
      <small>Bounded external evidence-provenance records; current index includes {notarial_count} notarial {notarial_word}. Not endorsement, philosophical validation, forensic identity proof, or canonical authority.</small>
    </a>
  </div>
  <p class="home-live-signal-boundary">
    These are operational and evidence signals, not a hierarchy. Reception does not imply autonomous discovery, endorsement, authority, amendment, or successor reception. External witness records do not imply endorsement, philosophical validation, forensic identity proof, or canonical authority. Native chain inventory remains API-only and is not used as the official reception counter. A receipt is intake-only, not final inclusion, and not active Guardian status.
  </p>
  <div class="home-status-links">
    <a href="/status/"><strong>System status</strong><span>Operational health and current evidence state</span></a>
    <a href="/record-chain/"><strong>Record-Chain</strong><span>Public records, indexes, and append history</span></a>
    <a href="/api/public-home-status.json"><strong>Machine status</strong><span>Current public counters and boundaries</span></a>
    <a href="/api/record-chain-status.json"><strong>Chain API</strong><span>Technical chain tip and durability state</span></a>
  </div>
  <p class="status-generated-note">Generated from <a href="/api/public-home-status.json">/api/public-home-status.json</a>. Source data digest <code>{source_digest}</code>. Latest technical record <code>{latest_record}</code>.</p>
</section>
{END}'''


render_detailed = render


def build_status(current: dict[str, Any], previous: dict[str, Any]) -> dict[str, Any]:
    records = load_records()
    config = sidecar()
    idx = visibility_index(config)
    current["schema"] = "trinityaccord.public-home-status.v3"
    if "source_digest" not in current:
        current["source_digest"] = digest()
    current.setdefault("generated_from", [])
    if SIDECAR_SOURCE not in current["generated_from"]:
        current["generated_from"].insert(0, SIDECAR_SOURCE)
    current["primary_counters"] = primary_counters(records, idx, config)
    current["technical_health"] = technical_health(current)
    current.setdefault("reception", {})["not_homepage_primary_counter"] = True
    candidate = dict(current)
    candidate["generated_at"] = datetime.now(timezone.utc).isoformat()
    if previous and without_generated_at(previous) == without_generated_at(candidate):
        candidate["generated_at"] = previous.get("generated_at", candidate["generated_at"])
    return candidate


def replace_block(text: str, rendered: str) -> str:
    new_text, count = re.subn(
        re.escape(BEGIN) + r".*?" + re.escape(END),
        rendered,
        text,
        count=1,
        flags=re.DOTALL,
    )
    if count != 1:
        raise SystemExit("failed to replace generated public status block")
    return new_text


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="Fail if patcher would change committed public status files")
    args = parser.parse_args()

    previous = read_committed_status()
    status = build_status(load(STATUS_PATH), previous)
    expected_json = dump(status)
    old_text = INDEX_MD.read_text(encoding="utf-8")
    new_text = replace_block(old_text, render(status))

    if args.check:
        errors: list[str] = []
        actual_json = STATUS_PATH.read_text(encoding="utf-8")
        if actual_json != expected_json:
            try:
                actual_data = json.loads(actual_json)
                expected_data = json.loads(expected_json)
                skip = {"generated_at", "source_digest"}
                actual_compare = {k: v for k, v in actual_data.items() if k not in skip}
                expected_compare = {k: v for k, v in expected_data.items() if k not in skip}
                if actual_compare != expected_compare:
                    errors.append("api/public-home-status.json is not patched to the canonical homepage primary-counter view")
            except (json.JSONDecodeError, KeyError):
                errors.append("api/public-home-status.json is not patched to the canonical homepage primary-counter view")
        if old_text != new_text:
            errors.append("index.md generated public status block is not patched to the canonical homepage primary-counter view")
        if errors:
            raise SystemExit("\n".join(errors))
        print("public homepage primary patch is up to date")
        return 0

    STATUS_PATH.write_text(expected_json, encoding="utf-8")
    if old_text != new_text:
        INDEX_MD.write_text(new_text, encoding="utf-8")
    print("patched public homepage primary counters and technical health")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
