#!/usr/bin/env node
import assert from 'assert/strict';
import fs from 'fs';
import { execFileSync } from 'child_process';

const wrapper = fs.readFileSync('scripts/build-chronicle-sidechain-evidence.mjs', 'utf8');
const corePath = 'scripts/build-chronicle-sidechain-evidence-core.mjs';
assert.ok(fs.existsSync(corePath), `sidechain evidence builder core missing: ${corePath}`);
const build = fs.readFileSync(corePath, 'utf8');
const rebuildPath = 'scripts/rebuild-chronicle-sidechain-cars-from-history.mjs';
const rebuildBasePath = 'scripts/rebuild-chronicle-sidechain-cars-from-history-base.mjs';
assert.ok(fs.existsSync(rebuildPath), `historical CAR rebuilder missing: ${rebuildPath}`);
assert.ok(fs.existsSync(rebuildBasePath), `historical CAR rebuilder base missing: ${rebuildBasePath}`);
execFileSync(process.execPath, ['--check', rebuildPath], { stdio: 'pipe' });
execFileSync(process.execPath, ['--check', rebuildBasePath], { stdio: 'pipe' });
const rebuild = fs.readFileSync(rebuildPath, 'utf8');
const rebuildBase = fs.readFileSync(rebuildBasePath, 'utf8');
const rebuildImplementation = `${rebuild}\n${rebuildBase}`;
const workflowPath = '.github/workflows/chronicle-sidechain-mirror-v3.yml';
assert.ok(fs.existsSync(workflowPath), `active sidechain workflow missing: ${workflowPath}`);
assert.ok(!fs.existsSync('.github/workflows/chronicle-sidechain-mirror.yml'), 'retired serial sidechain workflow must remain absent');
const workflow = fs.readFileSync(workflowPath, 'utf8');

assert.match(wrapper, /auditWholeCarCache/);
assert.match(wrapper, /installWholeDagFetchGuard/);
assert.match(wrapper, /rebuildCarsFromHistoricalPayloads/);
assert.match(wrapper, /cache_audit_after_historical_rebuild/);
assert.match(wrapper, /build-chronicle-sidechain-evidence-core\.mjs/);
assert.match(rebuildImplementation, /verifyCompleteCar/);
assert.match(rebuildImplementation, /cidSha256Digest/);
assert.match(rebuildImplementation, /kubo_unixfs_exact_root_match/);
assert.match(rebuildImplementation, /\['dag', 'export', rootCid\]/);
assert.match(rebuildImplementation, /computed !== rootCid/);
assert.match(rebuild, /baseRebuildCarsFromHistoricalPayloads/);
assert.match(rebuild, /kubo_exact_content_rebuild/);
assert.match(rebuild, /HISTORICAL-CONTENT-RECOVERY\.ndjson/);
assert.match(rebuild, /https:\/\/ipfs\.io\/ipfs\/\{cid\}/);
assert.match(rebuild, /https:\/\/nftstorage\.link\/ipfs\/\{cid\}/);
assert.match(build, /CHRONICLE_EVIDENCE_REFRESH_HISTORY/);
assert.match(build, /verified_recovered_tokens_snapshot/);
assert.match(build, /snapshotHistory\(t\)/);
assert.match(workflow, /CHRONICLE_EVIDENCE_REFRESH_HISTORY: "false"/);

const baseline = workflow.indexOf('Restore complete CAR baseline cache');
const latest = workflow.indexOf('Restore latest CAR and block recovery cache');
assert.ok(baseline >= 0 && latest > baseline, 'complete baseline must be restored before the latest block cache overlay');
assert.match(workflow, /chronicle-sidechain-cars-v2-d0fe9d4c5f57d98f784ea9c9726d762a0980c08c19b909e6bdc60e97e29be7c8-32078752685-1/);
assert.match(workflow, /CHRONICLE_HISTORICAL_CHUNK_SIZES: "1048576,262144"/);
assert.match(workflow, /https:\/\/ipfs\.raribleuserdata\.com\/ipfs\/\{cid\}/);
assert.match(workflow, /https:\/\/rarible\.mypinata\.cloud\/ipfs\/\{cid\}/);
assert.match(workflow, /KUBO_VERSION: 0\.37\.0/);
assert.match(workflow, /KUBO_LINUX_AMD64_SHA512: [0-9a-f]{128}/);
assert.match(workflow, /sha512sum --check --strict/);
assert.match(workflow, /daemon --migrate=false/);
assert.match(build, /CAR HISTORICAL CHUNK VERIFIED/);
assert.match(build, /scope: 'all'/);
assert.match(build, /CAR LASSIE ROOT REUSE/);
assert.match(build, /CAR KUBO BLOCK VERIFIED/);
assert.match(build, /singleBlockCar\(cid, data\)/);

console.log('[BOOTSTRAP HISTORY TEST PASS] strict wrapper + split historical payload/content CAR reconstruction + preserved snapshot history + layered CAR caches + active v3 workflow');
