#!/usr/bin/env python3
"""
Verify Claim Gate entrypoints are live on the deployed site.
Checks that mandatory Claim Gate references appear in online pages and APIs.

Usage:
    python3 scripts/verify_claim_gate_entrypoints_online.py
"""
import json
import sys
import urllib.request

BASE = "https://www.trinityaccord.org"

# Pages that must contain specific keywords
PAGE_CHECKS = [
    ("/llms.txt", "MANDATORY CLAIM GATE RULE"),
    ("/ai.txt", "claim gate"),
    ("/agent-brief", "Claim Gate"),
    ("/.well-known/agent.json", "mandatory_before_submission"),
    ("/api/agent-entry-protocol.json", "submission_gate"),
    ("/api/agent-submission-guide.json", "freeform_submission_policy"),
    ("/api/generated-by-schema.v1.json", "Generated By"),
    ("/api/provenance-consistency-rules.json", "provenance"),
    ("/api/issue-submission-policy.json", "claim_gate"),
    ("/api/verification-claim-scope.json", "verification_scope_label"),
    ("/api/verification-report-schema.v2.json", "verification_scope_label"),
    ("/api/echo-record-schema.v3.json", "verification_scope_label"),
    ("/api/report-builder-policy.json", "verification_scope_label"),
]

passed = 0
failed = 0


def fetch_text(path):
    url = f"{BASE}{path}"
    try:
        req = urllib.request.Request(url, headers={"User-Agent": "verify-claim-gate-entrypoints/1.0"})
        with urllib.request.urlopen(req, timeout=15) as resp:
            return resp.read().decode("utf-8"), None
    except Exception as e:
        return None, str(e)


def check_json_contains(path, key):
    """Fetch JSON and check if key appears in serialized form."""
    text, err = fetch_text(path)
    if err:
        return False, f"fetch error: {err}"
    try:
        data = json.loads(text)
        if key in json.dumps(data):
            return True, None
        return False, f"'{key}' not found in JSON"
    except json.JSONDecodeError:
        return False, "invalid JSON"


def check_text_contains(path, key):
    """Fetch text/HTML and check if key appears (case-insensitive for HTML)."""
    text, err = fetch_text(path)
    if err:
        return False, f"fetch error: {err}"
    if key.lower() in text.lower():
        return True, None
    return False, f"'{key}' not found in page content"


for path, keyword in PAGE_CHECKS:
    is_json = path.endswith(".json")
    if is_json:
        ok, detail = check_json_contains(path, keyword)
    else:
        ok, detail = check_text_contains(path, keyword)

    if ok:
        print(f"PASS: {path} contains '{keyword}'")
        passed += 1
    else:
        print(f"FAIL: {path} — {detail}")
        failed += 1

print(f"\n{'='*60}")
print(f"Results: {passed} PASS, {failed} FAIL")
if failed == 0:
    print("FINAL: PASS — claim gate entrypoints online verified.")
    sys.exit(0)
else:
    print("FINAL: FAIL — some claim gate entrypoint checks failed.")
    sys.exit(1)
